package localize

import "strings"

var options = []Option{
	{English, "English"}, {"ar", "العربية"}, {"bn", "বাংলা"}, {"ca", "Català"},
	{"cs", "Čeština"}, {"da", "Dansk"}, {"de", "Deutsch"}, {"el", "Ελληνικά"},
	{"es", "Español"}, {"fi", "Suomi"}, {"fr", "Français"}, {"he", "עברית"},
	{"hi", "हिन्दी"}, {"hr", "Hrvatski"}, {"hu", "Magyar"}, {"id", "Bahasa Indonesia"},
	{"it", "Italiano"}, {"ja", "日本語"}, {"ko", "한국어"}, {"nl", "Nederlands"},
	{"no", "Norsk"}, {"pl", "Polski"}, {"pt-BR", "Português (Brasil)"}, {"ro", "Română"},
	{"ru", "Русский"}, {"sk", "Slovenčina"}, {"sv", "Svenska"}, {"th", "ไทย"},
	{"tr", "Türkçe"}, {"uk", "Українська"}, {"vi", "Tiếng Việt"},
	{"zh-CN", "简体中文"}, {"zh-TW", "繁體中文"},
}

var catalog = map[Locale]map[string]string{
	English: englishCatalog,
	"ar":    words("نظرة عامة", "المواقع", "النشاط", "المراقبة", "قواعد البيانات", "التخزين", "مزودو DNS", "المستخدمون", "حسابي", "أدوات الموقع", "إعدادات الخادم", "الحساب والأمان", "تسجيل الخروج", "النسخ الاحتياطية", "الملفات", "بيئة الاختبار", "SSL والأمان", "السجلات والاستخدام", "الإعدادات", "إنشاء موقع", "المواقع الإجمالية", "موارد الخادم", "فتح المراقبة", "عرض كل المواقع"),
	"bn":    words("সংক্ষিপ্ত বিবরণ", "সাইটসমূহ", "কার্যকলাপ", "পর্যবেক্ষণ", "ডেটাবেস", "স্টোরেজ", "DNS প্রদানকারী", "ব্যবহারকারী", "আমার অ্যাকাউন্ট", "সাইটের সরঞ্জাম", "সার্ভার সেটিংস", "অ্যাকাউন্ট ও নিরাপত্তা", "সাইন আউট", "ব্যাকআপ", "ফাইল", "স্টেজিং", "SSL ও নিরাপত্তা", "লগ ও ব্যবহার", "সেটিংস", "সাইট তৈরি করুন", "মোট সাইট", "সার্ভার রিসোর্স", "পর্যবেক্ষণ খুলুন", "সব সাইট দেখুন"),
	"ca":    words("Resum", "Llocs", "Activitat", "Monitoratge", "Bases de dades", "Emmagatzematge", "Proveïdors DNS", "Usuaris", "El meu compte", "Eines del lloc", "Configuració del servidor", "Compte i seguretat", "Tanca la sessió", "Còpies de seguretat", "Fitxers", "Preproducció", "SSL i seguretat", "Registres i ús", "Configuració", "Crea un lloc", "Total de llocs", "Recursos del servidor", "Obre el monitoratge", "Mostra tots els llocs"),
	"cs":    words("Přehled", "Weby", "Aktivita", "Monitorování", "Databáze", "Úložiště", "Poskytovatelé DNS", "Uživatelé", "Můj účet", "Nástroje webu", "Nastavení serveru", "Účet a zabezpečení", "Odhlásit se", "Zálohy", "Soubory", "Testovací prostředí", "SSL a zabezpečení", "Protokoly a využití", "Nastavení", "Vytvořit web", "Celkem webů", "Prostředky serveru", "Otevřít monitorování", "Zobrazit všechny weby"),
	"da":    words("Oversigt", "Websteder", "Aktivitet", "Overvågning", "Databaser", "Lager", "DNS-udbydere", "Brugere", "Min konto", "Webstedsværktøjer", "Serverindstillinger", "Konto og sikkerhed", "Log ud", "Sikkerhedskopier", "Filer", "Testmiljø", "SSL og sikkerhed", "Logfiler og forbrug", "Indstillinger", "Opret websted", "Websteder i alt", "Serverressourcer", "Åbn overvågning", "Vis alle websteder"),
	"de":    words("Übersicht", "Websites", "Aktivität", "Überwachung", "Datenbanken", "Speicher", "DNS-Anbieter", "Benutzer", "Mein Konto", "Website-Werkzeuge", "Servereinstellungen", "Konto und Sicherheit", "Abmelden", "Sicherungen", "Dateien", "Testumgebung", "SSL und Sicherheit", "Protokolle und Nutzung", "Einstellungen", "Website erstellen", "Websites insgesamt", "Serverressourcen", "Überwachung öffnen", "Alle Websites anzeigen"),
	"el":    words("Επισκόπηση", "Ιστότοποι", "Δραστηριότητα", "Παρακολούθηση", "Βάσεις δεδομένων", "Αποθήκευση", "Πάροχοι DNS", "Χρήστες", "Ο λογαριασμός μου", "Εργαλεία ιστοτόπου", "Ρυθμίσεις διακομιστή", "Λογαριασμός και ασφάλεια", "Αποσύνδεση", "Αντίγραφα ασφαλείας", "Αρχεία", "Δοκιμαστικό περιβάλλον", "SSL και ασφάλεια", "Αρχεία καταγραφής και χρήση", "Ρυθμίσεις", "Δημιουργία ιστοτόπου", "Σύνολο ιστοτόπων", "Πόροι διακομιστή", "Άνοιγμα παρακολούθησης", "Προβολή όλων των ιστοτόπων"),
	"es":    words("Resumen", "Sitios", "Actividad", "Monitorización", "Bases de datos", "Almacenamiento", "Proveedores DNS", "Usuarios", "Mi cuenta", "Herramientas del sitio", "Ajustes del servidor", "Cuenta y seguridad", "Cerrar sesión", "Copias de seguridad", "Archivos", "Entorno de pruebas", "SSL y seguridad", "Registros y uso", "Ajustes", "Crear sitio", "Sitios totales", "Recursos del servidor", "Abrir monitorización", "Ver todos los sitios"),
	"fi":    words("Yleiskatsaus", "Sivustot", "Toiminta", "Valvonta", "Tietokannat", "Tallennustila", "DNS-palveluntarjoajat", "Käyttäjät", "Oma tili", "Sivuston työkalut", "Palvelimen asetukset", "Tili ja turvallisuus", "Kirjaudu ulos", "Varmuuskopiot", "Tiedostot", "Testiympäristö", "SSL ja turvallisuus", "Lokit ja käyttö", "Asetukset", "Luo sivusto", "Sivustoja yhteensä", "Palvelinresurssit", "Avaa valvonta", "Näytä kaikki sivustot"),
	"fr":    words("Vue d’ensemble", "Sites", "Activité", "Surveillance", "Bases de données", "Stockage", "Fournisseurs DNS", "Utilisateurs", "Mon compte", "Outils du site", "Paramètres du serveur", "Compte et sécurité", "Se déconnecter", "Sauvegardes", "Fichiers", "Préproduction", "SSL et sécurité", "Journaux et utilisation", "Paramètres", "Créer un site", "Nombre de sites", "Ressources du serveur", "Ouvrir la surveillance", "Voir tous les sites"),
	"he":    words("סקירה", "אתרים", "פעילות", "ניטור", "מסדי נתונים", "אחסון", "ספקי DNS", "משתמשים", "החשבון שלי", "כלי האתר", "הגדרות שרת", "חשבון ואבטחה", "יציאה", "גיבויים", "קבצים", "סביבת בדיקות", "SSL ואבטחה", "יומנים ושימוש", "הגדרות", "יצירת אתר", "סך האתרים", "משאבי שרת", "פתיחת ניטור", "הצגת כל האתרים"),
	"hi":    words("अवलोकन", "साइटें", "गतिविधि", "निगरानी", "डेटाबेस", "स्टोरेज", "DNS प्रदाता", "उपयोगकर्ता", "मेरा खाता", "साइट उपकरण", "सर्वर सेटिंग", "खाता और सुरक्षा", "साइन आउट", "बैकअप", "फ़ाइलें", "स्टेजिंग", "SSL और सुरक्षा", "लॉग और उपयोग", "सेटिंग", "साइट बनाएँ", "कुल साइटें", "सर्वर संसाधन", "निगरानी खोलें", "सभी साइटें देखें"),
	"hr":    words("Pregled", "Web-mjesta", "Aktivnost", "Nadzor", "Baze podataka", "Pohrana", "DNS pružatelji", "Korisnici", "Moj račun", "Alati web-mjesta", "Postavke poslužitelja", "Račun i sigurnost", "Odjava", "Sigurnosne kopije", "Datoteke", "Testno okruženje", "SSL i sigurnost", "Zapisi i upotreba", "Postavke", "Izradi web-mjesto", "Ukupno web-mjesta", "Resursi poslužitelja", "Otvori nadzor", "Prikaži sva web-mjesta"),
	"hu":    words("Áttekintés", "Webhelyek", "Tevékenység", "Felügyelet", "Adatbázisok", "Tárhely", "DNS-szolgáltatók", "Felhasználók", "Saját fiók", "Webhelyeszközök", "Kiszolgáló beállításai", "Fiók és biztonság", "Kijelentkezés", "Biztonsági mentések", "Fájlok", "Tesztkörnyezet", "SSL és biztonság", "Naplók és használat", "Beállítások", "Webhely létrehozása", "Webhelyek összesen", "Kiszolgáló-erőforrások", "Felügyelet megnyitása", "Összes webhely megtekintése"),
	"id":    words("Ringkasan", "Situs", "Aktivitas", "Pemantauan", "Basis data", "Penyimpanan", "Penyedia DNS", "Pengguna", "Akun saya", "Alat situs", "Pengaturan server", "Akun dan keamanan", "Keluar", "Cadangan", "File", "Lingkungan uji", "SSL dan keamanan", "Log dan penggunaan", "Pengaturan", "Buat situs", "Total situs", "Sumber daya server", "Buka pemantauan", "Lihat semua situs"),
	"it":    words("Panoramica", "Siti", "Attività", "Monitoraggio", "Database", "Archiviazione", "Provider DNS", "Utenti", "Il mio account", "Strumenti del sito", "Impostazioni server", "Account e sicurezza", "Esci", "Backup", "File", "Ambiente di test", "SSL e sicurezza", "Log e utilizzo", "Impostazioni", "Crea sito", "Siti totali", "Risorse del server", "Apri monitoraggio", "Visualizza tutti i siti"),
	"ja":    words("概要", "サイト", "アクティビティ", "監視", "データベース", "ストレージ", "DNSプロバイダー", "ユーザー", "マイアカウント", "サイトツール", "サーバー設定", "アカウントとセキュリティ", "ログアウト", "バックアップ", "ファイル", "ステージング", "SSLとセキュリティ", "ログと使用状況", "設定", "サイトを作成", "サイト総数", "サーバーリソース", "監視を開く", "すべてのサイトを表示"),
	"ko":    words("개요", "사이트", "활동", "모니터링", "데이터베이스", "저장소", "DNS 제공업체", "사용자", "내 계정", "사이트 도구", "서버 설정", "계정 및 보안", "로그아웃", "백업", "파일", "스테이징", "SSL 및 보안", "로그 및 사용량", "설정", "사이트 만들기", "전체 사이트", "서버 리소스", "모니터링 열기", "모든 사이트 보기"),
	"nl":    words("Overzicht", "Sites", "Activiteit", "Bewaking", "Databases", "Opslag", "DNS-providers", "Gebruikers", "Mijn account", "Sitehulpmiddelen", "Serverinstellingen", "Account en beveiliging", "Afmelden", "Back-ups", "Bestanden", "Testomgeving", "SSL en beveiliging", "Logboeken en gebruik", "Instellingen", "Site maken", "Totaal aantal sites", "Serverbronnen", "Bewaking openen", "Alle sites bekijken"),
	"no":    words("Oversikt", "Nettsteder", "Aktivitet", "Overvåking", "Databaser", "Lagring", "DNS-leverandører", "Brukere", "Min konto", "Nettstedverktøy", "Serverinnstillinger", "Konto og sikkerhet", "Logg ut", "Sikkerhetskopier", "Filer", "Testmiljø", "SSL og sikkerhet", "Logger og bruk", "Innstillinger", "Opprett nettsted", "Nettsteder totalt", "Serverressurser", "Åpne overvåking", "Vis alle nettsteder"),
	"pl":    words("Przegląd", "Witryny", "Aktywność", "Monitorowanie", "Bazy danych", "Pamięć", "Dostawcy DNS", "Użytkownicy", "Moje konto", "Narzędzia witryny", "Ustawienia serwera", "Konto i bezpieczeństwo", "Wyloguj się", "Kopie zapasowe", "Pliki", "Środowisko testowe", "SSL i bezpieczeństwo", "Dzienniki i użycie", "Ustawienia", "Utwórz witrynę", "Łączna liczba witryn", "Zasoby serwera", "Otwórz monitorowanie", "Wyświetl wszystkie witryny"),
	"pt-BR": words("Visão geral", "Sites", "Atividade", "Monitoramento", "Bancos de dados", "Armazenamento", "Provedores de DNS", "Usuários", "Minha conta", "Ferramentas do site", "Configurações do servidor", "Conta e segurança", "Sair", "Backups", "Arquivos", "Ambiente de teste", "SSL e segurança", "Logs e uso", "Configurações", "Criar site", "Total de sites", "Recursos do servidor", "Abrir monitoramento", "Ver todos os sites"),
	"ro":    words("Prezentare generală", "Site-uri", "Activitate", "Monitorizare", "Baze de date", "Stocare", "Furnizori DNS", "Utilizatori", "Contul meu", "Instrumente site", "Setări server", "Cont și securitate", "Deconectare", "Copii de siguranță", "Fișiere", "Mediu de testare", "SSL și securitate", "Jurnale și utilizare", "Setări", "Creează site", "Total site-uri", "Resurse server", "Deschide monitorizarea", "Vezi toate site-urile"),
	"ru":    words("Обзор", "Сайты", "Действия", "Мониторинг", "Базы данных", "Хранилище", "Провайдеры DNS", "Пользователи", "Моя учётная запись", "Инструменты сайта", "Настройки сервера", "Учётная запись и безопасность", "Выйти", "Резервные копии", "Файлы", "Тестовая среда", "SSL и безопасность", "Журналы и использование", "Настройки", "Создать сайт", "Всего сайтов", "Ресурсы сервера", "Открыть мониторинг", "Показать все сайты"),
	"sk":    words("Prehľad", "Weby", "Aktivita", "Monitorovanie", "Databázy", "Úložisko", "Poskytovatelia DNS", "Používatelia", "Môj účet", "Nástroje webu", "Nastavenia servera", "Účet a zabezpečenie", "Odhlásiť sa", "Zálohy", "Súbory", "Testovacie prostredie", "SSL a zabezpečenie", "Denníky a využitie", "Nastavenia", "Vytvoriť web", "Weby spolu", "Prostriedky servera", "Otvoriť monitorovanie", "Zobraziť všetky weby"),
	"sv":    words("Översikt", "Webbplatser", "Aktivitet", "Övervakning", "Databaser", "Lagring", "DNS-leverantörer", "Användare", "Mitt konto", "Webbplatsverktyg", "Serverinställningar", "Konto och säkerhet", "Logga ut", "Säkerhetskopior", "Filer", "Testmiljö", "SSL och säkerhet", "Loggar och användning", "Inställningar", "Skapa webbplats", "Totalt antal webbplatser", "Serverresurser", "Öppna övervakning", "Visa alla webbplatser"),
	"th":    words("ภาพรวม", "เว็บไซต์", "กิจกรรม", "การตรวจสอบ", "ฐานข้อมูล", "พื้นที่จัดเก็บ", "ผู้ให้บริการ DNS", "ผู้ใช้", "บัญชีของฉัน", "เครื่องมือเว็บไซต์", "การตั้งค่าเซิร์ฟเวอร์", "บัญชีและความปลอดภัย", "ออกจากระบบ", "ข้อมูลสำรอง", "ไฟล์", "สภาพแวดล้อมทดสอบ", "SSL และความปลอดภัย", "บันทึกและการใช้งาน", "การตั้งค่า", "สร้างเว็บไซต์", "เว็บไซต์ทั้งหมด", "ทรัพยากรเซิร์ฟเวอร์", "เปิดการตรวจสอบ", "ดูเว็บไซต์ทั้งหมด"),
	"tr":    words("Genel bakış", "Siteler", "Etkinlik", "İzleme", "Veritabanları", "Depolama", "DNS sağlayıcıları", "Kullanıcılar", "Hesabım", "Site araçları", "Sunucu ayarları", "Hesap ve güvenlik", "Çıkış yap", "Yedekler", "Dosyalar", "Test ortamı", "SSL ve güvenlik", "Günlükler ve kullanım", "Ayarlar", "Site oluştur", "Toplam site", "Sunucu kaynakları", "İzlemeyi aç", "Tüm siteleri görüntüle"),
	"uk":    words("Огляд", "Сайти", "Активність", "Моніторинг", "Бази даних", "Сховище", "Постачальники DNS", "Користувачі", "Мій обліковий запис", "Інструменти сайту", "Налаштування сервера", "Обліковий запис і безпека", "Вийти", "Резервні копії", "Файли", "Тестове середовище", "SSL і безпека", "Журнали та використання", "Налаштування", "Створити сайт", "Усього сайтів", "Ресурси сервера", "Відкрити моніторинг", "Переглянути всі сайти"),
	"vi":    words("Tổng quan", "Trang web", "Hoạt động", "Giám sát", "Cơ sở dữ liệu", "Lưu trữ", "Nhà cung cấp DNS", "Người dùng", "Tài khoản của tôi", "Công cụ trang web", "Cài đặt máy chủ", "Tài khoản và bảo mật", "Đăng xuất", "Bản sao lưu", "Tệp", "Môi trường thử nghiệm", "SSL và bảo mật", "Nhật ký và mức sử dụng", "Cài đặt", "Tạo trang web", "Tổng số trang web", "Tài nguyên máy chủ", "Mở giám sát", "Xem tất cả trang web"),
	"zh-CN": words("概览", "站点", "活动", "监控", "数据库", "存储", "DNS 提供商", "用户", "我的账户", "站点工具", "服务器设置", "账户与安全", "退出登录", "备份", "文件", "预发布环境", "SSL 与安全", "日志与用量", "设置", "创建站点", "站点总数", "服务器资源", "打开监控", "查看所有站点"),
	"zh-TW": words("總覽", "網站", "活動", "監控", "資料庫", "儲存空間", "DNS 供應商", "使用者", "我的帳戶", "網站工具", "伺服器設定", "帳戶與安全性", "登出", "備份", "檔案", "預備環境", "SSL 與安全性", "記錄與用量", "設定", "建立網站", "網站總數", "伺服器資源", "開啟監控", "檢視所有網站"),
}

var keys = []string{"overview", "sites", "activity", "monitoring", "databases", "storage", "dns_providers", "users", "my_account", "site_tools", "server_settings", "account_security", "sign_out", "backups", "files", "staging", "ssl_security", "logs_usage", "settings", "create_site", "total_sites", "server_resources", "open_monitoring", "view_all_sites"}

var englishCatalog = map[string]string{
	"overview": "Overview", "sites": "Sites", "activity": "Activity", "monitoring": "Monitoring",
	"databases": "Databases", "storage": "Storage", "dns_providers": "DNS providers", "users": "Users",
	"my_account": "My account", "site_tools": "Site tools", "server_settings": "Server settings",
	"account_security": "Account & security", "sign_out": "Sign out", "backups": "Backups", "files": "Files",
	"staging": "Staging", "ssl_security": "SSL & security", "logs_usage": "Logs & usage", "settings": "Settings",
	"create_site": "Create site", "total_sites": "Total sites", "server_resources": "Server resources",
	"open_monitoring": "Open monitoring", "view_all_sites": "View all sites",
	"language": "Language", "apply": "Apply",
	"wordpress": "WordPress", "dns": "DNS", "hosting": "Hosting", "alerts": "Alerts", "all_sites": "All sites",
	"site": "Site", "access": "Access", "security": "Security", "cron": "Cron", "runtime": "Runtime", "ftp": "FTP",
	"logs": "Logs", "account": "Account", "skip_to_content": "Skip to content", "server": "Server",
}

var selectorWords = map[Locale][2]string{
	"ar": {"اللغة", "تطبيق"}, "bn": {"ভাষা", "প্রয়োগ করুন"}, "ca": {"Idioma", "Aplica"},
	"cs": {"Jazyk", "Použít"}, "da": {"Sprog", "Anvend"}, "de": {"Sprache", "Anwenden"},
	"el": {"Γλώσσα", "Εφαρμογή"}, "es": {"Idioma", "Aplicar"}, "fi": {"Kieli", "Käytä"},
	"fr": {"Langue", "Appliquer"}, "he": {"שפה", "החלה"}, "hi": {"भाषा", "लागू करें"},
	"hr": {"Jezik", "Primijeni"}, "hu": {"Nyelv", "Alkalmaz"}, "id": {"Bahasa", "Terapkan"},
	"it": {"Lingua", "Applica"}, "ja": {"言語", "適用"}, "ko": {"언어", "적용"},
	"nl": {"Taal", "Toepassen"}, "no": {"Språk", "Bruk"}, "pl": {"Język", "Zastosuj"},
	"pt-BR": {"Idioma", "Aplicar"}, "ro": {"Limbă", "Aplică"}, "ru": {"Язык", "Применить"},
	"sk": {"Jazyk", "Použiť"}, "sv": {"Språk", "Använd"}, "th": {"ภาษา", "นำไปใช้"},
	"tr": {"Dil", "Uygula"}, "uk": {"Мова", "Застосувати"}, "vi": {"Ngôn ngữ", "Áp dụng"},
	"zh-CN": {"语言", "应用"}, "zh-TW": {"語言", "套用"},
}

var navigationWords = map[Locale][15]string{
	"ar":    {"ووردبريس", "DNS", "الاستضافة", "التنبيهات", "كل المواقع", "الموقع", "الوصول", "الأمان", "المهام المجدولة", "بيئة التشغيل", "FTP", "السجلات", "الحساب", "تخطي إلى المحتوى", "الخادم"},
	"bn":    {"ওয়ার্ডপ্রেস", "DNS", "হোস্টিং", "সতর্কতা", "সব সাইট", "সাইট", "অ্যাক্সেস", "নিরাপত্তা", "নির্ধারিত কাজ", "রানটাইম", "FTP", "লগ", "অ্যাকাউন্ট", "বিষয়বস্তুতে যান", "সার্ভার"},
	"ca":    {"WordPress", "DNS", "Allotjament", "Alertes", "Tots els llocs", "Lloc", "Accés", "Seguretat", "Tasques programades", "Entorn d’execució", "FTP", "Registres", "Compte", "Ves al contingut", "Servidor"},
	"cs":    {"WordPress", "DNS", "Hosting", "Upozornění", "Všechny weby", "Web", "Přístup", "Zabezpečení", "Plánované úlohy", "Běhové prostředí", "FTP", "Protokoly", "Účet", "Přejít k obsahu", "Server"},
	"da":    {"WordPress", "DNS", "Hosting", "Advarsler", "Alle websteder", "Websted", "Adgang", "Sikkerhed", "Planlagte opgaver", "Kørselsmiljø", "FTP", "Logfiler", "Konto", "Gå til indhold", "Server"},
	"de":    {"WordPress", "DNS", "Hosting", "Warnungen", "Alle Websites", "Website", "Zugriff", "Sicherheit", "Zeitgesteuerte Aufgaben", "Laufzeit", "FTP", "Protokolle", "Konto", "Zum Inhalt springen", "Server"},
	"el":    {"WordPress", "DNS", "Φιλοξενία", "Ειδοποιήσεις", "Όλοι οι ιστότοποι", "Ιστότοπος", "Πρόσβαση", "Ασφάλεια", "Προγραμματισμένες εργασίες", "Περιβάλλον εκτέλεσης", "FTP", "Αρχεία καταγραφής", "Λογαριασμός", "Μετάβαση στο περιεχόμενο", "Διακομιστής"},
	"es":    {"WordPress", "DNS", "Alojamiento", "Alertas", "Todos los sitios", "Sitio", "Acceso", "Seguridad", "Tareas programadas", "Entorno de ejecución", "FTP", "Registros", "Cuenta", "Saltar al contenido", "Servidor"},
	"fi":    {"WordPress", "DNS", "Verkkohotelli", "Hälytykset", "Kaikki sivustot", "Sivusto", "Käyttöoikeus", "Turvallisuus", "Ajastetut tehtävät", "Ajoympäristö", "FTP", "Lokit", "Tili", "Siirry sisältöön", "Palvelin"},
	"fr":    {"WordPress", "DNS", "Hébergement", "Alertes", "Tous les sites", "Site", "Accès", "Sécurité", "Tâches planifiées", "Environnement d’exécution", "FTP", "Journaux", "Compte", "Aller au contenu", "Serveur"},
	"he":    {"וורדפרס", "DNS", "אירוח", "התראות", "כל האתרים", "אתר", "גישה", "אבטחה", "משימות מתוזמנות", "סביבת ריצה", "FTP", "יומנים", "חשבון", "דילוג לתוכן", "שרת"},
	"hi":    {"वर्डप्रेस", "DNS", "होस्टिंग", "अलर्ट", "सभी साइटें", "साइट", "पहुँच", "सुरक्षा", "निर्धारित कार्य", "रनटाइम", "FTP", "लॉग", "खाता", "सामग्री पर जाएँ", "सर्वर"},
	"hr":    {"WordPress", "DNS", "Hosting", "Upozorenja", "Sva web-mjesta", "Web-mjesto", "Pristup", "Sigurnost", "Zakazani zadaci", "Izvršno okruženje", "FTP", "Zapisi", "Račun", "Preskoči na sadržaj", "Poslužitelj"},
	"hu":    {"WordPress", "DNS", "Tárhelyszolgáltatás", "Riasztások", "Összes webhely", "Webhely", "Hozzáférés", "Biztonság", "Ütemezett feladatok", "Futtatókörnyezet", "FTP", "Naplók", "Fiók", "Ugrás a tartalomhoz", "Kiszolgáló"},
	"id":    {"WordPress", "DNS", "Hosting", "Peringatan", "Semua situs", "Situs", "Akses", "Keamanan", "Tugas terjadwal", "Runtime", "FTP", "Log", "Akun", "Lewati ke konten", "Server"},
	"it":    {"WordPress", "DNS", "Hosting", "Avvisi", "Tutti i siti", "Sito", "Accesso", "Sicurezza", "Attività pianificate", "Runtime", "FTP", "Log", "Account", "Vai al contenuto", "Server"},
	"ja":    {"WordPress", "DNS", "ホスティング", "アラート", "すべてのサイト", "サイト", "アクセス", "セキュリティ", "スケジュール済みタスク", "ランタイム", "FTP", "ログ", "アカウント", "コンテンツへ移動", "サーバー"},
	"ko":    {"워드프레스", "DNS", "호스팅", "알림", "모든 사이트", "사이트", "접근", "보안", "예약 작업", "런타임", "FTP", "로그", "계정", "콘텐츠로 건너뛰기", "서버"},
	"nl":    {"WordPress", "DNS", "Hosting", "Meldingen", "Alle sites", "Site", "Toegang", "Beveiliging", "Geplande taken", "Runtime", "FTP", "Logboeken", "Account", "Naar inhoud", "Server"},
	"no":    {"WordPress", "DNS", "Hosting", "Varsler", "Alle nettsteder", "Nettsted", "Tilgang", "Sikkerhet", "Planlagte oppgaver", "Kjøremiljø", "FTP", "Logger", "Konto", "Gå til innhold", "Server"},
	"pl":    {"WordPress", "DNS", "Hosting", "Alerty", "Wszystkie witryny", "Witryna", "Dostęp", "Bezpieczeństwo", "Zaplanowane zadania", "Środowisko uruchomieniowe", "FTP", "Dzienniki", "Konto", "Przejdź do treści", "Serwer"},
	"pt-BR": {"WordPress", "DNS", "Hospedagem", "Alertas", "Todos os sites", "Site", "Acesso", "Segurança", "Tarefas agendadas", "Ambiente de execução", "FTP", "Logs", "Conta", "Pular para o conteúdo", "Servidor"},
	"ro":    {"WordPress", "DNS", "Găzduire", "Alerte", "Toate site-urile", "Site", "Acces", "Securitate", "Sarcini programate", "Mediu de execuție", "FTP", "Jurnale", "Cont", "Salt la conținut", "Server"},
	"ru":    {"WordPress", "DNS", "Хостинг", "Оповещения", "Все сайты", "Сайт", "Доступ", "Безопасность", "Запланированные задачи", "Среда выполнения", "FTP", "Журналы", "Учётная запись", "Перейти к содержимому", "Сервер"},
	"sk":    {"WordPress", "DNS", "Hosting", "Upozornenia", "Všetky weby", "Web", "Prístup", "Zabezpečenie", "Naplánované úlohy", "Behové prostredie", "FTP", "Denníky", "Účet", "Prejsť na obsah", "Server"},
	"sv":    {"WordPress", "DNS", "Webbhotell", "Varningar", "Alla webbplatser", "Webbplats", "Åtkomst", "Säkerhet", "Schemalagda uppgifter", "Körmiljö", "FTP", "Loggar", "Konto", "Hoppa till innehåll", "Server"},
	"th":    {"เวิร์ดเพรส", "DNS", "โฮสติ้ง", "การแจ้งเตือน", "เว็บไซต์ทั้งหมด", "เว็บไซต์", "การเข้าถึง", "ความปลอดภัย", "งานตามกำหนดเวลา", "สภาพแวดล้อมการทำงาน", "FTP", "บันทึก", "บัญชี", "ข้ามไปยังเนื้อหา", "เซิร์ฟเวอร์"},
	"tr":    {"WordPress", "DNS", "Barındırma", "Uyarılar", "Tüm siteler", "Site", "Erişim", "Güvenlik", "Zamanlanmış görevler", "Çalışma ortamı", "FTP", "Günlükler", "Hesap", "İçeriğe geç", "Sunucu"},
	"uk":    {"WordPress", "DNS", "Хостинг", "Сповіщення", "Усі сайти", "Сайт", "Доступ", "Безпека", "Заплановані завдання", "Середовище виконання", "FTP", "Журнали", "Обліковий запис", "Перейти до вмісту", "Сервер"},
	"vi":    {"WordPress", "DNS", "Lưu trữ web", "Cảnh báo", "Tất cả trang web", "Trang web", "Truy cập", "Bảo mật", "Tác vụ đã lên lịch", "Môi trường chạy", "FTP", "Nhật ký", "Tài khoản", "Chuyển đến nội dung", "Máy chủ"},
	"zh-CN": {"WordPress", "DNS", "托管", "警报", "所有站点", "站点", "访问", "安全", "计划任务", "运行环境", "FTP", "日志", "账户", "跳到内容", "服务器"},
	"zh-TW": {"WordPress", "DNS", "託管", "警示", "所有網站", "網站", "存取", "安全性", "排程工作", "執行環境", "FTP", "記錄", "帳戶", "跳至內容", "伺服器"},
}

var navigationKeys = [...]string{"wordpress", "dns", "hosting", "alerts", "all_sites", "site", "access", "security", "cron", "runtime", "ftp", "logs", "account", "skip_to_content", "server"}

// Action labels combine localized verbs with existing localized feature names.
// Keeping this vocabulary regular gives forms a broad, complete catalog while
// retaining reviewed native words instead of copying English aliases.
var actionKeys = [...]string{"create", "add", "save", "edit", "delete", "enable", "disable", "download", "upload", "restore", "verify", "install", "update"}
var actionWords = map[Locale][13]string{
	English: {"Create", "Add", "Save", "Edit", "Delete", "Enable", "Disable", "Download", "Upload", "Restore", "Verify", "Install", "Update"},
	"ar":    {"إنشاء", "إضافة", "حفظ", "تعديل", "حذف", "تمكين", "تعطيل", "تنزيل", "رفع", "استعادة", "تحقق من", "تثبيت", "تحديث"},
	"bn":    {"তৈরি করুন", "যোগ করুন", "সংরক্ষণ করুন", "সম্পাদনা করুন", "মুছুন", "সক্রিয় করুন", "নিষ্ক্রিয় করুন", "ডাউনলোড করুন", "আপলোড করুন", "পুনরুদ্ধার করুন", "যাচাই করুন", "ইনস্টল করুন", "আপডেট করুন"},
	"ca":    {"Crea", "Afegeix", "Desa", "Edita", "Suprimeix", "Activa", "Desactiva", "Baixa", "Puja", "Restaura", "Verifica", "Instal·la", "Actualitza"},
	"cs":    {"Vytvořit", "Přidat", "Uložit", "Upravit", "Smazat", "Povolit", "Zakázat", "Stáhnout", "Nahrát", "Obnovit", "Ověřit", "Nainstalovat", "Aktualizovat"},
	"da":    {"Opret", "Tilføj", "Gem", "Rediger", "Slet", "Aktivér", "Deaktivér", "Download", "Upload", "Gendan", "Bekræft", "Installér", "Opdater"},
	"de":    {"Erstellen", "Hinzufügen", "Speichern", "Bearbeiten", "Löschen", "Aktivieren", "Deaktivieren", "Herunterladen", "Hochladen", "Wiederherstellen", "Prüfen", "Installieren", "Aktualisieren"},
	"el":    {"Δημιουργία", "Προσθήκη", "Αποθήκευση", "Επεξεργασία", "Διαγραφή", "Ενεργοποίηση", "Απενεργοποίηση", "Λήψη", "Μεταφόρτωση", "Επαναφορά", "Επαλήθευση", "Εγκατάσταση", "Ενημέρωση"},
	"es":    {"Crear", "Añadir", "Guardar", "Editar", "Eliminar", "Activar", "Desactivar", "Descargar", "Subir", "Restaurar", "Verificar", "Instalar", "Actualizar"},
	"fi":    {"Luo", "Lisää", "Tallenna", "Muokkaa", "Poista", "Ota käyttöön", "Poista käytöstä", "Lataa", "Lähetä", "Palauta", "Vahvista", "Asenna", "Päivitä"},
	"fr":    {"Créer", "Ajouter", "Enregistrer", "Modifier", "Supprimer", "Activer", "Désactiver", "Télécharger", "Importer", "Restaurer", "Vérifier", "Installer", "Mettre à jour"},
	"he":    {"יצירה", "הוספה", "שמירה", "עריכה", "מחיקה", "הפעלה", "השבתה", "הורדה", "העלאה", "שחזור", "אימות", "התקנה", "עדכון"},
	"hi":    {"बनाएँ", "जोड़ें", "सहेजें", "संपादित करें", "हटाएँ", "सक्षम करें", "अक्षम करें", "डाउनलोड करें", "अपलोड करें", "पुनर्स्थापित करें", "सत्यापित करें", "इंस्टॉल करें", "अपडेट करें"},
	"hr":    {"Izradi", "Dodaj", "Spremi", "Uredi", "Izbriši", "Omogući", "Onemogući", "Preuzmi", "Prenesi", "Vrati", "Provjeri", "Instaliraj", "Ažuriraj"},
	"hu":    {"Létrehozás", "Hozzáadás", "Mentés", "Szerkesztés", "Törlés", "Engedélyezés", "Letiltás", "Letöltés", "Feltöltés", "Visszaállítás", "Ellenőrzés", "Telepítés", "Frissítés"},
	"id":    {"Buat", "Tambah", "Simpan", "Edit", "Hapus", "Aktifkan", "Nonaktifkan", "Unduh", "Unggah", "Pulihkan", "Verifikasi", "Instal", "Perbarui"},
	"it":    {"Crea", "Aggiungi", "Salva", "Modifica", "Elimina", "Abilita", "Disabilita", "Scarica", "Carica", "Ripristina", "Verifica", "Installa", "Aggiorna"},
	"ja":    {"作成", "追加", "保存", "編集", "削除", "有効化", "無効化", "ダウンロード", "アップロード", "復元", "確認", "インストール", "更新"},
	"ko":    {"만들기", "추가", "저장", "편집", "삭제", "활성화", "비활성화", "다운로드", "업로드", "복원", "확인", "설치", "업데이트"},
	"nl":    {"Maken", "Toevoegen", "Opslaan", "Bewerken", "Verwijderen", "Inschakelen", "Uitschakelen", "Downloaden", "Uploaden", "Herstellen", "Verifiëren", "Installeren", "Bijwerken"},
	"no":    {"Opprett", "Legg til", "Lagre", "Rediger", "Slett", "Aktiver", "Deaktiver", "Last ned", "Last opp", "Gjenopprett", "Bekreft", "Installer", "Oppdater"},
	"pl":    {"Utwórz", "Dodaj", "Zapisz", "Edytuj", "Usuń", "Włącz", "Wyłącz", "Pobierz", "Prześlij", "Przywróć", "Zweryfikuj", "Zainstaluj", "Zaktualizuj"},
	"pt-BR": {"Criar", "Adicionar", "Salvar", "Editar", "Excluir", "Ativar", "Desativar", "Baixar", "Enviar", "Restaurar", "Verificar", "Instalar", "Atualizar"},
	"ro":    {"Creează", "Adaugă", "Salvează", "Editează", "Șterge", "Activează", "Dezactivează", "Descarcă", "Încarcă", "Restaurează", "Verifică", "Instalează", "Actualizează"},
	"ru":    {"Создать", "Добавить", "Сохранить", "Изменить", "Удалить", "Включить", "Отключить", "Скачать", "Загрузить", "Восстановить", "Проверить", "Установить", "Обновить"},
	"sk":    {"Vytvoriť", "Pridať", "Uložiť", "Upraviť", "Odstrániť", "Povoliť", "Zakázať", "Stiahnuť", "Nahrať", "Obnoviť", "Overiť", "Nainštalovať", "Aktualizovať"},
	"sv":    {"Skapa", "Lägg till", "Spara", "Redigera", "Ta bort", "Aktivera", "Inaktivera", "Ladda ned", "Ladda upp", "Återställ", "Verifiera", "Installera", "Uppdatera"},
	"th":    {"สร้าง", "เพิ่ม", "บันทึก", "แก้ไข", "ลบ", "เปิดใช้", "ปิดใช้", "ดาวน์โหลด", "อัปโหลด", "กู้คืน", "ตรวจสอบ", "ติดตั้ง", "อัปเดต"},
	"tr":    {"Oluştur", "Ekle", "Kaydet", "Düzenle", "Sil", "Etkinleştir", "Devre dışı bırak", "İndir", "Yükle", "Geri yükle", "Doğrula", "Kur", "Güncelle"},
	"uk":    {"Створити", "Додати", "Зберегти", "Редагувати", "Видалити", "Увімкнути", "Вимкнути", "Завантажити", "Вивантажити", "Відновити", "Перевірити", "Встановити", "Оновити"},
	"vi":    {"Tạo", "Thêm", "Lưu", "Chỉnh sửa", "Xóa", "Bật", "Tắt", "Tải xuống", "Tải lên", "Khôi phục", "Xác minh", "Cài đặt", "Cập nhật"},
	"zh-CN": {"创建", "添加", "保存", "编辑", "删除", "启用", "禁用", "下载", "上传", "恢复", "验证", "安装", "更新"},
	"zh-TW": {"建立", "新增", "儲存", "編輯", "刪除", "啟用", "停用", "下載", "上傳", "還原", "驗證", "安裝", "更新"},
}

var fieldKeys = [...]string{"name", "status", "label", "username", "password", "email", "host", "port", "sender", "recipient", "subject", "threshold", "cpu", "memory", "disk", "service", "certificate", "expiry", "enabled", "disabled", "active", "failed", "pending", "cancel", "copy", "cut", "paste", "rename", "search", "size"}

var fieldWords = map[Locale]string{
	English: "Name|Status|Label|Username|Password|Email|Host|Port|Sender|Recipient|Subject|Threshold|CPU|Memory|Disk|Service|Certificate|Expiry|Enabled|Disabled|Active|Failed|Pending|Cancel|Copy|Cut|Paste|Rename|Search|Size",
	"ar":    "الاسم|الحالة|التسمية|اسم المستخدم|كلمة المرور|البريد الإلكتروني|المضيف|المنفذ|المرسل|المستلم|الموضوع|الحد|المعالج|الذاكرة|القرص|الخدمة|الشهادة|انتهاء الصلاحية|مُمكّن|معطّل|نشط|فشل|قيد الانتظار|إلغاء|نسخ|قص|لصق|إعادة تسمية|بحث|الحجم",
	"bn":    "নাম|অবস্থা|লেবেল|ব্যবহারকারীর নাম|পাসওয়ার্ড|ইমেইল|হোস্ট|পোর্ট|প্রেরক|প্রাপক|বিষয়|সীমা|CPU|মেমরি|ডিস্ক|পরিষেবা|সার্টিফিকেট|মেয়াদ শেষ|সক্রিয়|নিষ্ক্রিয়|চালু|ব্যর্থ|অপেক্ষমাণ|বাতিল|কপি|কাট|পেস্ট|নাম পরিবর্তন|অনুসন্ধান|আকার",
	"ca":    "Nom|Estat|Etiqueta|Nom d’usuari|Contrasenya|Correu electrònic|Amfitrió|Port|Remitent|Destinatari|Assumpte|Llindar|CPU|Memòria|Disc|Servei|Certificat|Caducitat|Activat|Desactivat|Actiu|Fallat|Pendent|Cancel·la|Copia|Retalla|Enganxa|Canvia el nom|Cerca|Mida",
	"cs":    "Název|Stav|Štítek|Uživatelské jméno|Heslo|E-mail|Hostitel|Port|Odesílatel|Příjemce|Předmět|Prahová hodnota|CPU|Paměť|Disk|Služba|Certifikát|Platnost do|Povoleno|Zakázáno|Aktivní|Selhalo|Čeká|Zrušit|Kopírovat|Vyjmout|Vložit|Přejmenovat|Hledat|Velikost",
	"da":    "Navn|Status|Etiket|Brugernavn|Adgangskode|E-mail|Vært|Port|Afsender|Modtager|Emne|Tærskel|CPU|Hukommelse|Disk|Tjeneste|Certifikat|Udløb|Aktiveret|Deaktiveret|Aktiv|Mislykket|Afventer|Annuller|Kopiér|Klip|Indsæt|Omdøb|Søg|Størrelse",
	"de":    "Name|Status|Bezeichnung|Benutzername|Passwort|E-Mail|Host|Port|Absender|Empfänger|Betreff|Schwellenwert|CPU|Arbeitsspeicher|Festplatte|Dienst|Zertifikat|Ablauf|Aktiviert|Deaktiviert|Aktiv|Fehlgeschlagen|Ausstehend|Abbrechen|Kopieren|Ausschneiden|Einfügen|Umbenennen|Suchen|Größe",
	"el":    "Όνομα|Κατάσταση|Ετικέτα|Όνομα χρήστη|Κωδικός πρόσβασης|Email|Κεντρικός υπολογιστής|Θύρα|Αποστολέας|Παραλήπτης|Θέμα|Όριο|CPU|Μνήμη|Δίσκος|Υπηρεσία|Πιστοποιητικό|Λήξη|Ενεργοποιημένο|Απενεργοποιημένο|Ενεργό|Απέτυχε|Σε αναμονή|Ακύρωση|Αντιγραφή|Αποκοπή|Επικόλληση|Μετονομασία|Αναζήτηση|Μέγεθος",
	"es":    "Nombre|Estado|Etiqueta|Nombre de usuario|Contraseña|Correo electrónico|Host|Puerto|Remitente|Destinatario|Asunto|Umbral|CPU|Memoria|Disco|Servicio|Certificado|Caducidad|Activado|Desactivado|Activo|Fallido|Pendiente|Cancelar|Copiar|Cortar|Pegar|Renombrar|Buscar|Tamaño",
	"fi":    "Nimi|Tila|Tunniste|Käyttäjänimi|Salasana|Sähköposti|Isäntä|Portti|Lähettäjä|Vastaanottaja|Aihe|Raja|CPU|Muisti|Levy|Palvelu|Varmenne|Vanhentuminen|Käytössä|Poistettu käytöstä|Aktiivinen|Epäonnistui|Odottaa|Peruuta|Kopioi|Leikkaa|Liitä|Nimeä uudelleen|Hae|Koko",
	"fr":    "Nom|État|Libellé|Nom d’utilisateur|Mot de passe|E-mail|Hôte|Port|Expéditeur|Destinataire|Objet|Seuil|CPU|Mémoire|Disque|Service|Certificat|Expiration|Activé|Désactivé|Actif|Échec|En attente|Annuler|Copier|Couper|Coller|Renommer|Rechercher|Taille",
	"he":    "שם|מצב|תווית|שם משתמש|סיסמה|דוא״ל|מארח|יציאה|שולח|נמען|נושא|סף|מעבד|זיכרון|דיסק|שירות|אישור|תפוגה|מופעל|מושבת|פעיל|נכשל|ממתין|ביטול|העתקה|גזירה|הדבקה|שינוי שם|חיפוש|גודל",
	"hi":    "नाम|स्थिति|लेबल|उपयोगकर्ता नाम|पासवर्ड|ईमेल|होस्ट|पोर्ट|प्रेषक|प्राप्तकर्ता|विषय|सीमा|CPU|मेमोरी|डिस्क|सेवा|प्रमाणपत्र|समाप्ति|सक्षम|अक्षम|सक्रिय|विफल|लंबित|रद्द करें|कॉपी|कट|पेस्ट|नाम बदलें|खोजें|आकार",
	"hr":    "Naziv|Status|Oznaka|Korisničko ime|Lozinka|E-pošta|Poslužitelj|Priključak|Pošiljatelj|Primatelj|Predmet|Prag|CPU|Memorija|Disk|Usluga|Certifikat|Istek|Omogućeno|Onemogućeno|Aktivno|Neuspjelo|Na čekanju|Odustani|Kopiraj|Izreži|Zalijepi|Preimenuj|Traži|Veličina",
	"hu":    "Név|Állapot|Címke|Felhasználónév|Jelszó|E-mail|Gazdagép|Port|Feladó|Címzett|Tárgy|Küszöb|CPU|Memória|Lemez|Szolgáltatás|Tanúsítvány|Lejárat|Engedélyezve|Letiltva|Aktív|Sikertelen|Függőben|Mégse|Másolás|Kivágás|Beillesztés|Átnevezés|Keresés|Méret",
	"id":    "Nama|Status|Label|Nama pengguna|Kata sandi|Email|Host|Port|Pengirim|Penerima|Subjek|Ambang|CPU|Memori|Disk|Layanan|Sertifikat|Kedaluwarsa|Diaktifkan|Dinonaktifkan|Aktif|Gagal|Tertunda|Batal|Salin|Potong|Tempel|Ubah nama|Cari|Ukuran",
	"it":    "Nome|Stato|Etichetta|Nome utente|Password|Email|Host|Porta|Mittente|Destinatario|Oggetto|Soglia|CPU|Memoria|Disco|Servizio|Certificato|Scadenza|Abilitato|Disabilitato|Attivo|Non riuscito|In sospeso|Annulla|Copia|Taglia|Incolla|Rinomina|Cerca|Dimensione",
	"ja":    "名前|状態|ラベル|ユーザー名|パスワード|メール|ホスト|ポート|送信者|受信者|件名|しきい値|CPU|メモリ|ディスク|サービス|証明書|有効期限|有効|無効|稼働中|失敗|保留中|キャンセル|コピー|切り取り|貼り付け|名前を変更|検索|サイズ",
	"ko":    "이름|상태|레이블|사용자 이름|비밀번호|이메일|호스트|포트|보낸 사람|받는 사람|제목|임계값|CPU|메모리|디스크|서비스|인증서|만료|활성화됨|비활성화됨|활성|실패|대기 중|취소|복사|잘라내기|붙여넣기|이름 바꾸기|검색|크기",
	"nl":    "Naam|Status|Label|Gebruikersnaam|Wachtwoord|E-mail|Host|Poort|Afzender|Ontvanger|Onderwerp|Drempel|CPU|Geheugen|Schijf|Dienst|Certificaat|Vervaldatum|Ingeschakeld|Uitgeschakeld|Actief|Mislukt|In afwachting|Annuleren|Kopiëren|Knippen|Plakken|Hernoemen|Zoeken|Grootte",
	"no":    "Navn|Status|Etikett|Brukernavn|Passord|E-post|Vert|Port|Avsender|Mottaker|Emne|Terskel|CPU|Minne|Disk|Tjeneste|Sertifikat|Utløp|Aktivert|Deaktivert|Aktiv|Mislyktes|Venter|Avbryt|Kopier|Klipp ut|Lim inn|Gi nytt navn|Søk|Størrelse",
	"pl":    "Nazwa|Stan|Etykieta|Nazwa użytkownika|Hasło|E-mail|Host|Port|Nadawca|Odbiorca|Temat|Próg|CPU|Pamięć|Dysk|Usługa|Certyfikat|Wygaśnięcie|Włączone|Wyłączone|Aktywne|Niepowodzenie|Oczekujące|Anuluj|Kopiuj|Wytnij|Wklej|Zmień nazwę|Szukaj|Rozmiar",
	"pt-BR": "Nome|Status|Rótulo|Nome de usuário|Senha|Email|Host|Porta|Remetente|Destinatário|Assunto|Limite|CPU|Memória|Disco|Serviço|Certificado|Validade|Ativado|Desativado|Ativo|Falhou|Pendente|Cancelar|Copiar|Recortar|Colar|Renomear|Pesquisar|Tamanho",
	"ro":    "Nume|Stare|Etichetă|Nume de utilizator|Parolă|E-mail|Gazdă|Port|Expeditor|Destinatar|Subiect|Prag|CPU|Memorie|Disc|Serviciu|Certificat|Expirare|Activat|Dezactivat|Activ|Eșuat|În așteptare|Anulează|Copiază|Decupează|Lipește|Redenumește|Caută|Dimensiune",
	"ru":    "Имя|Состояние|Метка|Имя пользователя|Пароль|Эл. почта|Хост|Порт|Отправитель|Получатель|Тема|Порог|ЦП|Память|Диск|Служба|Сертификат|Истечение|Включено|Отключено|Активно|Ошибка|Ожидание|Отмена|Копировать|Вырезать|Вставить|Переименовать|Поиск|Размер",
	"sk":    "Názov|Stav|Štítok|Používateľské meno|Heslo|E-mail|Hostiteľ|Port|Odosielateľ|Príjemca|Predmet|Prahová hodnota|CPU|Pamäť|Disk|Služba|Certifikát|Platnosť do|Povolené|Zakázané|Aktívne|Zlyhalo|Čaká|Zrušiť|Kopírovať|Vystrihnúť|Prilepiť|Premenovať|Hľadať|Veľkosť",
	"sv":    "Namn|Status|Etikett|Användarnamn|Lösenord|E-post|Värd|Port|Avsändare|Mottagare|Ämne|Tröskel|CPU|Minne|Disk|Tjänst|Certifikat|Utgång|Aktiverad|Inaktiverad|Aktiv|Misslyckad|Väntande|Avbryt|Kopiera|Klipp ut|Klistra in|Byt namn|Sök|Storlek",
	"th":    "ชื่อ|สถานะ|ป้ายกำกับ|ชื่อผู้ใช้|รหัสผ่าน|อีเมล|โฮสต์|พอร์ต|ผู้ส่ง|ผู้รับ|หัวเรื่อง|เกณฑ์|CPU|หน่วยความจำ|ดิสก์|บริการ|ใบรับรอง|วันหมดอายุ|เปิดใช้|ปิดใช้|ใช้งานอยู่|ล้มเหลว|รอดำเนินการ|ยกเลิก|คัดลอก|ตัด|วาง|เปลี่ยนชื่อ|ค้นหา|ขนาด",
	"tr":    "Ad|Durum|Etiket|Kullanıcı adı|Parola|E-posta|Ana makine|Bağlantı noktası|Gönderen|Alıcı|Konu|Eşik|CPU|Bellek|Disk|Hizmet|Sertifika|Son kullanma|Etkin|Devre dışı|Aktif|Başarısız|Beklemede|İptal|Kopyala|Kes|Yapıştır|Yeniden adlandır|Ara|Boyut",
	"uk":    "Назва|Стан|Мітка|Ім’я користувача|Пароль|Ел. пошта|Хост|Порт|Відправник|Одержувач|Тема|Поріг|ЦП|Пам’ять|Диск|Служба|Сертифікат|Закінчення|Увімкнено|Вимкнено|Активно|Помилка|Очікування|Скасувати|Копіювати|Вирізати|Вставити|Перейменувати|Пошук|Розмір",
	"vi":    "Tên|Trạng thái|Nhãn|Tên người dùng|Mật khẩu|Email|Máy chủ|Cổng|Người gửi|Người nhận|Chủ đề|Ngưỡng|CPU|Bộ nhớ|Ổ đĩa|Dịch vụ|Chứng chỉ|Hết hạn|Đã bật|Đã tắt|Đang hoạt động|Thất bại|Đang chờ|Hủy|Sao chép|Cắt|Dán|Đổi tên|Tìm kiếm|Kích thước",
	"zh-CN": "名称|状态|标签|用户名|密码|电子邮件|主机|端口|发件人|收件人|主题|阈值|CPU|内存|磁盘|服务|证书|到期时间|已启用|已禁用|活动|失败|待处理|取消|复制|剪切|粘贴|重命名|搜索|大小",
	"zh-TW": "名稱|狀態|標籤|使用者名稱|密碼|電子郵件|主機|連接埠|寄件者|收件者|主旨|閾值|CPU|記憶體|磁碟|服務|憑證|到期時間|已啟用|已停用|作用中|失敗|待處理|取消|複製|剪下|貼上|重新命名|搜尋|大小",
}

var fileKeys = [...]string{"new_folder", "archive", "extract", "refresh", "more_actions", "clear_selection", "no_selection", "selected", "select_all", "directory", "uploads", "clear_finished", "close"}

var fileWords = map[Locale]string{
	English: "New folder|Archive|Extract|Refresh|More actions|Clear selection|No selection|Selected|Select all|Directory|Uploads|Clear finished|Close",
	"ar":    "مجلد جديد|أرشفة|استخراج|تحديث|إجراءات إضافية|مسح التحديد|لا يوجد تحديد|محدد|تحديد الكل|الدليل|عمليات الرفع|مسح المكتمل|إغلاق",
	"bn":    "নতুন ফোল্ডার|আর্কাইভ|এক্সট্র্যাক্ট|রিফ্রেশ|আরও কাজ|নির্বাচন মুছুন|কিছু নির্বাচিত নয়|নির্বাচিত|সব নির্বাচন করুন|ডিরেক্টরি|আপলোড|সম্পন্নগুলো মুছুন|বন্ধ করুন",
	"ca":    "Carpeta nova|Arxiva|Extreu|Actualitza|Més accions|Neteja la selecció|Cap selecció|Seleccionats|Selecciona-ho tot|Directori|Càrregues|Neteja els acabats|Tanca",
	"cs":    "Nová složka|Archivovat|Rozbalit|Obnovit|Další akce|Zrušit výběr|Nic není vybráno|Vybráno|Vybrat vše|Adresář|Nahrávání|Vymazat dokončené|Zavřít",
	"da":    "Ny mappe|Arkivér|Udpak|Opdater|Flere handlinger|Ryd markering|Intet valgt|Valgt|Vælg alle|Mappe|Uploads|Ryd færdige|Luk",
	"de":    "Neuer Ordner|Archivieren|Entpacken|Aktualisieren|Weitere Aktionen|Auswahl aufheben|Keine Auswahl|Ausgewählt|Alle auswählen|Verzeichnis|Uploads|Fertige entfernen|Schließen",
	"el":    "Νέος φάκελος|Αρχειοθέτηση|Εξαγωγή|Ανανέωση|Περισσότερες ενέργειες|Εκκαθάριση επιλογής|Καμία επιλογή|Επιλεγμένα|Επιλογή όλων|Κατάλογος|Μεταφορτώσεις|Εκκαθάριση ολοκληρωμένων|Κλείσιμο",
	"es":    "Nueva carpeta|Archivar|Extraer|Actualizar|Más acciones|Borrar selección|Sin selección|Seleccionados|Seleccionar todo|Directorio|Subidas|Borrar finalizadas|Cerrar",
	"fi":    "Uusi kansio|Arkistoi|Pura|Päivitä|Lisää toimintoja|Tyhjennä valinta|Ei valintaa|Valittu|Valitse kaikki|Hakemisto|Lähetykset|Tyhjennä valmiit|Sulje",
	"fr":    "Nouveau dossier|Archiver|Extraire|Actualiser|Plus d’actions|Effacer la sélection|Aucune sélection|Sélectionnés|Tout sélectionner|Répertoire|Importations|Effacer les terminés|Fermer",
	"he":    "תיקייה חדשה|יצירת ארכיון|חילוץ|רענון|פעולות נוספות|ניקוי הבחירה|אין בחירה|נבחרו|בחירת הכול|תיקייה|העלאות|ניקוי שהושלמו|סגירה",
	"hi":    "नया फ़ोल्डर|संग्रहित करें|निकालें|रीफ़्रेश करें|और कार्रवाइयाँ|चयन साफ़ करें|कोई चयन नहीं|चयनित|सभी चुनें|डायरेक्टरी|अपलोड|पूर्ण हटाएँ|बंद करें",
	"hr":    "Nova mapa|Arhiviraj|Raspakiraj|Osvježi|Više radnji|Poništi odabir|Ništa nije odabrano|Odabrano|Odaberi sve|Direktorij|Prijenosi|Ukloni dovršeno|Zatvori",
	"hu":    "Új mappa|Archiválás|Kibontás|Frissítés|További műveletek|Kijelölés törlése|Nincs kijelölés|Kijelölve|Összes kijelölése|Könyvtár|Feltöltések|Befejezettek törlése|Bezárás",
	"id":    "Folder baru|Arsipkan|Ekstrak|Segarkan|Tindakan lainnya|Hapus pilihan|Tidak ada pilihan|Dipilih|Pilih semua|Direktori|Unggahan|Hapus yang selesai|Tutup",
	"it":    "Nuova cartella|Archivia|Estrai|Aggiorna|Altre azioni|Cancella selezione|Nessuna selezione|Selezionati|Seleziona tutto|Directory|Caricamenti|Rimuovi completati|Chiudi",
	"ja":    "新しいフォルダー|アーカイブ|展開|更新|その他の操作|選択を解除|選択なし|選択済み|すべて選択|ディレクトリ|アップロード|完了を消去|閉じる",
	"ko":    "새 폴더|보관|압축 풀기|새로 고침|추가 작업|선택 해제|선택 없음|선택됨|모두 선택|디렉터리|업로드|완료 항목 지우기|닫기",
	"nl":    "Nieuwe map|Archiveren|Uitpakken|Vernieuwen|Meer acties|Selectie wissen|Geen selectie|Geselecteerd|Alles selecteren|Map|Uploads|Voltooide wissen|Sluiten",
	"no":    "Ny mappe|Arkiver|Pakk ut|Oppdater|Flere handlinger|Fjern markering|Ingenting valgt|Valgt|Velg alle|Mappe|Opplastinger|Fjern fullførte|Lukk",
	"pl":    "Nowy folder|Archiwizuj|Rozpakuj|Odśwież|Więcej działań|Wyczyść zaznaczenie|Brak zaznaczenia|Wybrano|Zaznacz wszystko|Katalog|Przesyłanie|Wyczyść ukończone|Zamknij",
	"pt-BR": "Nova pasta|Arquivar|Extrair|Atualizar|Mais ações|Limpar seleção|Nenhuma seleção|Selecionados|Selecionar tudo|Diretório|Envios|Limpar concluídos|Fechar",
	"ro":    "Dosar nou|Arhivează|Extrage|Reîmprospătează|Mai multe acțiuni|Șterge selecția|Nicio selecție|Selectate|Selectează tot|Director|Încărcări|Șterge finalizate|Închide",
	"ru":    "Новая папка|Архивировать|Извлечь|Обновить|Другие действия|Снять выделение|Ничего не выбрано|Выбрано|Выбрать всё|Каталог|Загрузки|Очистить завершённые|Закрыть",
	"sk":    "Nový priečinok|Archivovať|Rozbaliť|Obnoviť|Ďalšie akcie|Zrušiť výber|Nič nie je vybrané|Vybrané|Vybrať všetko|Priečinok|Nahrávania|Vymazať dokončené|Zavrieť",
	"sv":    "Ny mapp|Arkivera|Packa upp|Uppdatera|Fler åtgärder|Rensa markering|Inget valt|Valda|Markera alla|Katalog|Uppladdningar|Rensa slutförda|Stäng",
	"th":    "โฟลเดอร์ใหม่|เก็บถาวร|แตกไฟล์|รีเฟรช|การดำเนินการเพิ่มเติม|ล้างการเลือก|ไม่มีการเลือก|เลือกแล้ว|เลือกทั้งหมด|ไดเรกทอรี|การอัปโหลด|ล้างรายการที่เสร็จแล้ว|ปิด",
	"tr":    "Yeni klasör|Arşivle|Çıkart|Yenile|Diğer işlemler|Seçimi temizle|Seçim yok|Seçildi|Tümünü seç|Dizin|Yüklemeler|Tamamlananları temizle|Kapat",
	"uk":    "Нова папка|Архівувати|Розпакувати|Оновити|Інші дії|Очистити вибір|Нічого не вибрано|Вибрано|Вибрати все|Каталог|Вивантаження|Очистити завершені|Закрити",
	"vi":    "Thư mục mới|Lưu trữ|Giải nén|Làm mới|Thao tác khác|Xóa lựa chọn|Chưa chọn|Đã chọn|Chọn tất cả|Thư mục|Tệp tải lên|Xóa mục hoàn tất|Đóng",
	"zh-CN": "新建文件夹|归档|解压|刷新|更多操作|清除选择|未选择|已选择|全选|目录|上传|清除已完成|关闭",
	"zh-TW": "新增資料夾|封存|解壓縮|重新整理|更多操作|清除選取|未選取|已選取|全選|目錄|上傳|清除已完成|關閉",
}

var commonKeys = [...]string{"appearance", "preferences", "system", "light", "dark", "ip_address", "http_status", "http_method", "path", "all_requests", "errors", "apply_filters", "clear_filters", "schedule", "account_settings", "slack", "telegram"}

var commonWords = map[Locale]string{
	English: "Appearance|Preferences|System|Light|Dark|IP address|HTTP status|HTTP method|Path|All requests|Errors|Apply filters|Clear filters|Schedule|Account settings|Slack|Telegram",
	"ar":    "المظهر|التفضيلات|النظام|فاتح|داكن|عنوان IP|حالة HTTP|طريقة HTTP|المسار|كل الطلبات|الأخطاء|تطبيق عوامل التصفية|مسح عوامل التصفية|الجدول|إعدادات الحساب|Slack|Telegram",
	"bn":    "চেহারা|পছন্দসমূহ|সিস্টেম|হালকা|গাঢ়|IP ঠিকানা|HTTP অবস্থা|HTTP পদ্ধতি|পথ|সব অনুরোধ|ত্রুটি|ফিল্টার প্রয়োগ করুন|ফিল্টার মুছুন|সময়সূচি|অ্যাকাউন্ট সেটিংস|Slack|Telegram",
	"ca":    "Aparença|Preferències|Sistema|Clar|Fosc|Adreça IP|Estat HTTP|Mètode HTTP|Camí|Totes les sol·licituds|Errors|Aplica els filtres|Neteja els filtres|Programació|Configuració del compte|Slack|Telegram",
	"cs":    "Vzhled|Předvolby|Systém|Světlý|Tmavý|IP adresa|Stav HTTP|Metoda HTTP|Cesta|Všechny požadavky|Chyby|Použít filtry|Vymazat filtry|Plán|Nastavení účtu|Slack|Telegram",
	"da":    "Udseende|Præferencer|System|Lys|Mørk|IP-adresse|HTTP-status|HTTP-metode|Sti|Alle anmodninger|Fejl|Anvend filtre|Ryd filtre|Tidsplan|Kontoindstillinger|Slack|Telegram",
	"de":    "Darstellung|Präferenzen|System|Hell|Dunkel|IP-Adresse|HTTP-Status|HTTP-Methode|Pfad|Alle Anfragen|Fehler|Filter anwenden|Filter zurücksetzen|Zeitplan|Kontoeinstellungen|Slack|Telegram",
	"el":    "Εμφάνιση|Προτιμήσεις|Σύστημα|Φωτεινό|Σκούρο|Διεύθυνση IP|Κατάσταση HTTP|Μέθοδος HTTP|Διαδρομή|Όλα τα αιτήματα|Σφάλματα|Εφαρμογή φίλτρων|Εκκαθάριση φίλτρων|Πρόγραμμα|Ρυθμίσεις λογαριασμού|Slack|Telegram",
	"es":    "Apariencia|Preferencias|Sistema|Claro|Oscuro|Dirección IP|Estado HTTP|Método HTTP|Ruta|Todas las solicitudes|Errores|Aplicar filtros|Borrar filtros|Programación|Configuración de la cuenta|Slack|Telegram",
	"fi":    "Ulkoasu|Määritykset|Järjestelmä|Vaalea|Tumma|IP-osoite|HTTP-tila|HTTP-menetelmä|Polku|Kaikki pyynnöt|Virheet|Käytä suodattimia|Tyhjennä suodattimet|Aikataulu|Tilin asetukset|Slack|Telegram",
	"fr":    "Apparence|Préférences|Système|Clair|Sombre|Adresse IP|Statut HTTP|Méthode HTTP|Chemin|Toutes les requêtes|Erreurs|Appliquer les filtres|Effacer les filtres|Planification|Paramètres du compte|Slack|Telegram",
	"he":    "מראה|העדפות|מערכת|בהיר|כהה|כתובת IP|מצב HTTP|שיטת HTTP|נתיב|כל הבקשות|שגיאות|החלת מסננים|ניקוי מסננים|לוח זמנים|הגדרות חשבון|Slack|Telegram",
	"hi":    "रूप-रंग|प्राथमिकताएँ|सिस्टम|हल्का|गहरा|IP पता|HTTP स्थिति|HTTP विधि|पथ|सभी अनुरोध|त्रुटियाँ|फ़िल्टर लागू करें|फ़िल्टर साफ़ करें|अनुसूची|खाता सेटिंग|Slack|Telegram",
	"hr":    "Izgled|Postavke|Sustav|Svijetlo|Tamno|IP adresa|HTTP status|HTTP metoda|Putanja|Svi zahtjevi|Pogreške|Primijeni filtre|Očisti filtre|Raspored|Postavke računa|Slack|Telegram",
	"hu":    "Megjelenés|Beállítások|Rendszer|Világos|Sötét|IP-cím|HTTP-állapot|HTTP-metódus|Elérési út|Minden kérés|Hibák|Szűrők alkalmazása|Szűrők törlése|Ütemezés|Fiókbeállítások|Slack|Telegram",
	"id":    "Tampilan|Preferensi|Sistem|Terang|Gelap|Alamat IP|Status HTTP|Metode HTTP|Jalur|Semua permintaan|Kesalahan|Terapkan filter|Hapus filter|Jadwal|Pengaturan akun|Slack|Telegram",
	"it":    "Aspetto|Preferenze|Sistema|Chiaro|Scuro|Indirizzo IP|Stato HTTP|Metodo HTTP|Percorso|Tutte le richieste|Errori|Applica filtri|Cancella filtri|Pianificazione|Impostazioni account|Slack|Telegram",
	"ja":    "外観|設定|システム|ライト|ダーク|IPアドレス|HTTPステータス|HTTPメソッド|パス|すべてのリクエスト|エラー|フィルターを適用|フィルターをクリア|スケジュール|アカウント設定|Slack|Telegram",
	"ko":    "모양|환경설정|시스템|라이트|다크|IP 주소|HTTP 상태|HTTP 메서드|경로|모든 요청|오류|필터 적용|필터 지우기|일정|계정 설정|Slack|Telegram",
	"nl":    "Weergave|Voorkeuren|Systeem|Licht|Donker|IP-adres|HTTP-status|HTTP-methode|Pad|Alle verzoeken|Fouten|Filters toepassen|Filters wissen|Planning|Accountinstellingen|Slack|Telegram",
	"no":    "Utseende|Innstillinger|System|Lys|Mørk|IP-adresse|HTTP-status|HTTP-metode|Sti|Alle forespørsler|Feil|Bruk filtre|Tøm filtre|Tidsplan|Kontoinnstillinger|Slack|Telegram",
	"pl":    "Wygląd|Preferencje|System|Jasny|Ciemny|Adres IP|Status HTTP|Metoda HTTP|Ścieżka|Wszystkie żądania|Błędy|Zastosuj filtry|Wyczyść filtry|Harmonogram|Ustawienia konta|Slack|Telegram",
	"pt-BR": "Aparência|Preferências|Sistema|Claro|Escuro|Endereço IP|Status HTTP|Método HTTP|Caminho|Todas as solicitações|Erros|Aplicar filtros|Limpar filtros|Agendamento|Configurações da conta|Slack|Telegram",
	"ro":    "Aspect|Preferințe|Sistem|Luminos|Întunecat|Adresă IP|Stare HTTP|Metodă HTTP|Cale|Toate solicitările|Erori|Aplică filtrele|Șterge filtrele|Program|Setări cont|Slack|Telegram",
	"ru":    "Оформление|Предпочтения|Система|Светлая|Тёмная|IP-адрес|Статус HTTP|Метод HTTP|Путь|Все запросы|Ошибки|Применить фильтры|Сбросить фильтры|Расписание|Настройки учётной записи|Slack|Telegram",
	"sk":    "Vzhľad|Predvoľby|Systém|Svetlý|Tmavý|IP adresa|Stav HTTP|Metóda HTTP|Cesta|Všetky požiadavky|Chyby|Použiť filtre|Vymazať filtre|Plán|Nastavenia účtu|Slack|Telegram",
	"sv":    "Utseende|Inställningar|System|Ljust|Mörkt|IP-adress|HTTP-status|HTTP-metod|Sökväg|Alla förfrågningar|Fel|Tillämpa filter|Rensa filter|Schema|Kontoinställningar|Slack|Telegram",
	"th":    "รูปลักษณ์|การกำหนดลักษณะ|ระบบ|สว่าง|มืด|ที่อยู่ IP|สถานะ HTTP|เมธอด HTTP|เส้นทาง|คำขอทั้งหมด|ข้อผิดพลาด|ใช้ตัวกรอง|ล้างตัวกรอง|กำหนดการ|การตั้งค่าบัญชี|Slack|Telegram",
	"tr":    "Görünüm|Tercihler|Sistem|Açık|Koyu|IP adresi|HTTP durumu|HTTP yöntemi|Yol|Tüm istekler|Hatalar|Filtreleri uygula|Filtreleri temizle|Zamanlama|Hesap ayarları|Slack|Telegram",
	"uk":    "Вигляд|Уподобання|Система|Світла|Темна|IP-адреса|Статус HTTP|Метод HTTP|Шлях|Усі запити|Помилки|Застосувати фільтри|Очистити фільтри|Розклад|Налаштування облікового запису|Slack|Telegram",
	"vi":    "Giao diện|Tùy chọn|Hệ thống|Sáng|Tối|Địa chỉ IP|Trạng thái HTTP|Phương thức HTTP|Đường dẫn|Tất cả yêu cầu|Lỗi|Áp dụng bộ lọc|Xóa bộ lọc|Lịch biểu|Cài đặt tài khoản|Slack|Telegram",
	"zh-CN": "外观|偏好设置|系统|浅色|深色|IP 地址|HTTP 状态|HTTP 方法|路径|所有请求|错误|应用筛选条件|清除筛选条件|计划|账户设置|Slack|Telegram",
	"zh-TW": "外觀|偏好設定|系統|淺色|深色|IP 位址|HTTP 狀態|HTTP 方法|路徑|所有要求|錯誤|套用篩選條件|清除篩選條件|排程|帳戶設定|Slack|Telegram",
}

var alpha18Keys = [...]string{"request_logs", "requests", "advanced_filters", "copy_requests", "last_200_requests", "raw_nginx_error_log", "search_and_replace", "find", "replace_with", "preview_changes", "dry_run_preview", "tables_scanned", "matches_in_preview", "recovery_storage", "select_storage", "back_up_and_apply", "preview_expired", "wp_search_scope", "preview_before_apply", "no_replacements_found", "search_text_required", "search_text_too_long", "backup_history", "source", "requested", "duration", "result", "scheduled", "manual", "success", "running", "queued", "restore_point_ready", "no_longer_retained", "backup_failed", "view_job", "no_backup_runs_yet", "sign_in_name", "username_or_email", "current_password", "update_sign_in_name", "edit_user", "role", "role_permissions", "administrator", "collaborator", "customer", "administrator_permissions", "collaborator_permissions", "customer_permissions", "debug", "wordpress_debug_mode", "wordpress_debug_log", "clear_log", "no_debug_entries", "recent_entries", "private_server_log", "debug_log_limit", "debug_errors_hidden", "configuration_needs_attention"}

var alpha18Words = map[Locale]string{
	English: "Request logs|Requests|Advanced filters|Copy requests|Last 200 requests|Raw Nginx error log|Search and replace|Find|Replace with|Preview changes|Dry-run preview|Tables scanned|Matches in preview|Recovery storage|Select storage|Back up and apply|Preview expired. Run the preview again.|Only this site's WordPress tables are searched. GUID columns are skipped.|Run a preview before applying changes.|No replacements found.|Search text is required.|Search text must be 1,024 characters or fewer.|Backup history|Source|Requested|Duration|Result|Scheduled|Manual|Success|Running|Queued|Restore point ready|No longer retained|Backup failed|View job|No backup runs yet|Sign-in name|Username or email|Current password|Update sign-in name|Edit user|Role|Role permissions|Administrator|Collaborator|Customer|Manages the server, users, and all sites.|Manages assigned sites.|Manages backups, logs, and WordPress for assigned sites.|Debug|Debug mode|WordPress debug log|Clear log|No debug entries yet.|Recent entries|Private server log|The log is limited to the most recent 256 KiB.|Errors stay hidden from visitors.|Configuration needs attention",
	"ar":    "سجلات الطلب|الطلبات|مرشحات متقدمة|نسخ الطلبات|آخر 200 طلب|سجل أخطاء Nginx الخام|بحث واستبدال|البحث عن|استبدل ب|معاينة التغييرات|معاينة التشغيل الجاف|الجداول الممسوحة ضوئيا|التطابقات في المعاينة|تخزين الاسترداد|حدد التخزين|النسخ الاحتياطي والتطبيق|انتهت المعاينة. قم بتشغيل المعاينة مرة أخرى.|يتم البحث فقط في جداول WordPress الخاصة بهذا الموقع. يتم تخطي أعمدة GUID.|قم بإجراء معاينة قبل تطبيق التغييرات.|لم يتم العثور على بدائل.|مطلوب نص البحث.|يجب أن يكون نص البحث 1024 حرفًا أو أقل.|تاريخ النسخ الاحتياطي|المصدر|مطلوب|المدة|النتيجة|المقرر|دليل|النجاح|الجري|في قائمة الانتظار|نقطة الاستعادة جاهزة|لم تعد محفوظة|فشل النسخ الاحتياطي|عرض الوظيفة|لم يتم تشغيل النسخ الاحتياطي حتى الآن|اسم تسجيل الدخول|اسم المستخدم أو البريد الإلكتروني|كلمة المرور الحالية|تحديث اسم تسجيل الدخول|تحرير المستخدم|الدور|أذونات الدور|المسؤول|متعاون|العميل|يدير الخادم والمستخدمين وجميع المواقع.|يدير المواقع المخصصة.|يدير النسخ الاحتياطية والسجلات وWordPress للمواقع المخصصة.|تصحيح|وضع التصحيح|سجل تصحيح ووردبريس|مسح السجل|لا توجد إدخالات تصحيح حتى الآن.|الإدخالات الأخيرة|سجل الخادم الخاص|يقتصر السجل على أحدث 256 كيلو بايت.|تظل الأخطاء مخفية عن الزوار.|التكوين يحتاج إلى الاهتمام",
	"bn":    "অনুরোধ লগ|অনুরোধ|উন্নত ফিল্টার|অনুলিপি অনুরোধ|শেষ 200টি অনুরোধ|কাঁচা Nginx ত্রুটি লগ|অনুসন্ধান এবং প্রতিস্থাপন|খুঁজুন|দিয়ে প্রতিস্থাপন করুন|পূর্বরূপ পরিবর্তন|ড্রাই-রান প্রিভিউ|টেবিল স্ক্যান করা হয়েছে|প্রিভিউতে মিল|পুনরুদ্ধার সঞ্চয়স্থান|স্টোরেজ নির্বাচন করুন|ব্যাক আপ এবং আবেদন|পূর্বরূপের মেয়াদ শেষ। আবার পূর্বরূপ চালান.|শুধুমাত্র এই সাইটের ওয়ার্ডপ্রেস টেবিল অনুসন্ধান করা হয়. GUID কলাম এড়িয়ে গেছে।|পরিবর্তনগুলি প্রয়োগ করার আগে একটি পূর্বরূপ চালান৷|কোন প্রতিস্থাপন পাওয়া যায়নি.|সার্চ টেক্সট প্রয়োজন.|অনুসন্ধান পাঠ্য অবশ্যই 1,024 অক্ষর বা তার কম হতে হবে।|ব্যাকআপ ইতিহাস|উৎস|অনুরোধ করেছেন|সময়কাল|ফলাফল|নির্ধারিত|ম্যানুয়াল|সফলতা|চলছে|সারিবদ্ধ|পুনরুদ্ধার পয়েন্ট প্রস্তুত|আর ধরে রাখা হয়নি|ব্যাকআপ ব্যর্থ হয়েছে৷|চাকরি দেখুন|এখনও কোনো ব্যাকআপ রান নেই|সাইন ইন নাম|ব্যবহারকারীর নাম বা ইমেল|বর্তমান পাসওয়ার্ড|সাইন-ইন নাম আপডেট করুন|ব্যবহারকারী সম্পাদনা করুন|ভূমিকা|ভূমিকা অনুমতি|প্রশাসক|সহযোগী|গ্রাহক|সার্ভার, ব্যবহারকারী এবং সমস্ত সাইট পরিচালনা করে।|নির্ধারিত সাইট পরিচালনা করে।|নির্ধারিত সাইটগুলির জন্য ব্যাকআপ, লগ এবং ওয়ার্ডপ্রেস পরিচালনা করে।|ডিবাগ|ডিবাগ মোড|ওয়ার্ডপ্রেস ডিবাগ লগ|সাফ লগ|এখনো কোনো ডিবাগ এন্ট্রি নেই৷|সাম্প্রতিক এন্ট্রি|ব্যক্তিগত সার্ভার লগ|লগটি সাম্প্রতিকতম 256 KiB এর মধ্যে সীমাবদ্ধ।|ত্রুটি দর্শকদের থেকে লুকানো থাকে.|কনফিগারেশন মনোযোগ প্রয়োজন",
	"ca":    "Sol·licitud de registres|Sol·licituds|Filtres avançats|Còpia de sol·licituds|Últimes 200 peticions|Registre d'errors de Nginx en brut|Cerca i substitueix|Troba|Substitueix per|Previsualitza els canvis|Vista prèvia de la tirada en sec|Taules escanejades|Partits en vista prèvia|Emmagatzematge de recuperació|Seleccioneu emmagatzematge|Fes una còpia de seguretat i aplica|La vista prèvia ha caducat. Torna a executar la vista prèvia.|Només es cerquen les taules de WordPress d'aquest lloc. Les columnes GUID s'han omès.|Executeu una previsualització abans d'aplicar els canvis.|No s'han trobat substitucions.|El text de cerca és obligatori.|El text de cerca ha de tenir 1.024 caràcters o menys.|Historial de còpies de seguretat|Font|Sol·licitat|Durada|Resultat|Programat|Manual|Èxit|Córrer|En cua|Punt de restauració llest|Ja no es conserva|La còpia de seguretat ha fallat|Veure feina|Encara no hi ha cap còpia de seguretat|Nom d'inici de sessió|Nom d'usuari o correu electrònic|Contrasenya actual|Actualitza el nom d'inici de sessió|Edita l'usuari|Rol|Permisos de rol|Administrador|Col·laborador|Client|Gestiona el servidor, els usuaris i tots els llocs.|Gestiona els llocs assignats.|Gestiona còpies de seguretat, registres i WordPress per als llocs assignats.|Depuració|Mode de depuració|Registre de depuració de WordPress|Esborra el registre|Encara no hi ha entrades de depuració.|Entrades recents|Registre del servidor privat|El registre es limita als 256 KiB més recents.|Els errors romanen ocults als visitants.|La configuració necessita atenció",
	"cs":    "Vyžádejte si protokoly|Žádosti|Pokročilé filtry|Kopírovat požadavky|Posledních 200 žádostí|Nezpracovaný protokol chyb Nginx|Hledat a nahradit|Najít|Nahradit za|Náhled změn|Náhled běhu nasucho|Naskenované tabulky|Shody v náhledu|Úložiště pro obnovu|Vyberte úložiště|Zálohujte a použijte|Platnost náhledu vypršela. Spusťte náhled znovu.|Prohledávají se pouze tabulky WordPress tohoto webu. Sloupce GUID jsou přeskočeny.|Před použitím změn spusťte náhled.|Nebyly nalezeny žádné náhrady.|Je vyžadován hledaný text.|Hledaný text musí mít 1 024 znaků nebo méně.|Historie zálohování|Zdroj|Vyžádáno|Doba trvání|Výsledek|Naplánováno|Manuál|Úspěch|Běh|Ve frontě|Bod obnovení připraven|Již neuchováváno|Zálohování se nezdařilo|Zobrazit práci|Dosud neprobíhá žádná záloha|Přihlašovací jméno|Uživatelské jméno nebo email|Aktuální heslo|Aktualizujte přihlašovací jméno|Upravit uživatele|Role|Oprávnění role|Správce|Spolupracovník|Zákazník|Spravuje server, uživatele a všechny weby.|Spravuje přiřazené weby.|Spravuje zálohy, protokoly a WordPress pro přiřazené weby.|Ladit|Režim ladění|Protokol ladění WordPress|Vymazat protokol|Zatím žádné položky ladění.|Nedávné záznamy|Protokol soukromého serveru|Záznam je omezen na nejnovějších 256 kB.|Chyby zůstávají návštěvníkům skryté.|Konfigurace vyžaduje pozornost",
	"da":    "Anmod om logs|Forespørgsler|Avancerede filtre|Kopier anmodninger|Seneste 200 anmodninger|Raw Nginx fejllog|Søg og erstat|Find|Udskift med|Forhåndsvisning af ændringer|Forhåndsvisning af tørløb|Borde scannet|Kampe i forhåndsvisning|Opbevaring til gendannelse|Vælg lager|Sikkerhedskopier og ansøg|Forhåndsvisningen er udløbet. Kør forhåndsvisningen igen.|Der søges kun i denne sides WordPress-tabeller. GUID-kolonner springes over.|Kør et eksempel, før du anvender ændringer.|Ingen erstatninger fundet.|Søgetekst er påkrævet.|Søgetekst skal være på 1.024 tegn eller derunder.|Backup historie|Kilde|Anmodet|Varighed|Resultat|Planlagt|Manual|Succes|Løb|I kø|Gendannelsespunktet er klar|Ikke længere bevaret|Sikkerhedskopiering mislykkedes|Se job|Ingen backup kører endnu|Log ind navn|Brugernavn eller e-mail|Nuværende adgangskode|Opdater loginnavn|Rediger bruger|Rolle|Rolletilladelser|Administrator|Samarbejdspartner|Kunde|Administrerer serveren, brugerne og alle websteder.|Administrerer tildelte websteder.|Administrerer sikkerhedskopier, logfiler og WordPress for tildelte websteder.|Debug|Fejlretningstilstand|WordPress debug log|Ryd log|Ingen fejlretningsposter endnu.|Seneste poster|Privat serverlog|Loggen er begrænset til de seneste 256 KiB.|Fejl forbliver skjult for besøgende.|Konfiguration kræver opmærksomhed",
	"de":    "Anfrageprotokolle|Anfragen|Erweiterte Filter|Kopieranfragen|Letzte 200 Anfragen|Rohes Nginx-Fehlerprotokoll|Suchen und ersetzen|Finden|Ersetzen durch|Vorschau der Änderungen|Probelaufvorschau|Tabellen gescannt|Übereinstimmungen in der Vorschau|Wiederherstellungsspeicher|Speicher auswählen|Sichern und anwenden|Vorschau abgelaufen. Führen Sie die Vorschau erneut aus.|Es werden nur die WordPress-Tabellen dieser Website durchsucht. GUID-Spalten werden übersprungen.|Führen Sie eine Vorschau aus, bevor Sie Änderungen übernehmen.|Kein Ersatz gefunden.|Suchtext ist erforderlich.|Der Suchtext darf maximal 1.024 Zeichen lang sein.|Backup-Verlauf|Quelle|Angefordert|Dauer|Ergebnis|Geplant|Handbuch|Erfolg|Laufen|In der Warteschlange|Wiederherstellungspunkt bereit|Wird nicht mehr beibehalten|Die Sicherung ist fehlgeschlagen|Job ansehen|Es wird noch kein Backup ausgeführt|Anmeldename|Benutzername oder E-Mail|Aktuelles Passwort|Anmeldenamen aktualisieren|Benutzer bearbeiten|Rolle|Rollenberechtigungen|Administrator|Mitarbeiter|Kunde|Verwaltet den Server, die Benutzer und alle Websites.|Verwaltet zugewiesene Standorte.|Verwaltet Backups, Protokolle und WordPress für zugewiesene Sites.|Debuggen|Debug-Modus|WordPress-Debug-Protokoll|Protokoll löschen|Noch keine Debug-Einträge.|Aktuelle Einträge|Privates Serverprotokoll|Das Protokoll ist auf die aktuellsten 256 KiB beschränkt.|Fehler bleiben für Besucher verborgen.|Die Konfiguration erfordert Aufmerksamkeit",
	"el":    "Αρχεία καταγραφής αιτημάτων|Αιτήματα|Προηγμένα φίλτρα|Αντιγραφή αιτημάτων|Τα τελευταία 200 αιτήματα|Μητρώο σφαλμάτων Raw Nginx|Αναζήτηση και αντικατάσταση|Βρείτε|Αντικατάσταση με|Προεπισκόπηση αλλαγών|Προεπισκόπηση ξηρής λειτουργίας|Οι πίνακες σαρώθηκαν|Αγώνες σε προεπισκόπηση|Αποθήκευση ανάκτησης|Επιλέξτε χώρο αποθήκευσης|Δημιουργήστε αντίγραφα ασφαλείας και εφαρμόστε|Η προεπισκόπηση έληξε. Εκτελέστε ξανά την προεπισκόπηση.|Γίνεται αναζήτηση μόνο στους πίνακες WordPress αυτού του ιστότοπου. Οι στήλες GUID παραλείπονται.|Εκτελέστε μια προεπισκόπηση πριν εφαρμόσετε αλλαγές.|Δεν βρέθηκαν αντικαταστάτες.|Απαιτείται κείμενο αναζήτησης.|Το κείμενο αναζήτησης πρέπει να αποτελείται από 1.024 χαρακτήρες ή λιγότερους.|Ιστορικό δημιουργίας αντιγράφων ασφαλείας|Πηγή|Ζητήθηκε|Διάρκεια|Αποτέλεσμα|Προγραμματισμένο|Εγχειρίδιο|Επιτυχία|Τρέξιμο|Σε ουρά|Έτοιμο το σημείο επαναφοράς|Δεν διατηρείται πλέον|Η δημιουργία αντιγράφων ασφαλείας απέτυχε|Προβολή εργασίας|Δεν εκτελούνται ακόμα αντίγραφα ασφαλείας|Όνομα σύνδεσης|Όνομα χρήστη ή email|Τρέχων κωδικός πρόσβασης|Ενημέρωση ονόματος σύνδεσης|Επεξεργασία χρήστη|Ρόλος|Δικαιώματα ρόλων|Διαχειριστής|Συνεργάτης|Πελάτης|Διαχειρίζεται τον διακομιστή, τους χρήστες και όλους τους ιστότοπους.|Διαχειρίζεται τους εκχωρημένους ιστότοπους.|Διαχειρίζεται αντίγραφα ασφαλείας, αρχεία καταγραφής και WordPress για εκχωρημένους ιστότοπους.|Εντοπισμός σφαλμάτων|Λειτουργία εντοπισμού σφαλμάτων|Αρχείο καταγραφής εντοπισμού σφαλμάτων WordPress|Εκκαθάριση αρχείου καταγραφής|Δεν υπάρχουν ακόμη καταχωρίσεις εντοπισμού σφαλμάτων.|Πρόσφατες καταχωρήσεις|Αρχείο καταγραφής ιδιωτικού διακομιστή|Το αρχείο καταγραφής περιορίζεται στα πιο πρόσφατα 256 KiB.|Τα σφάλματα παραμένουν κρυφά από τους επισκέπτες.|Η διαμόρφωση θέλει προσοχή",
	"es":    "Registros de solicitudes|Solicitudes|Filtros avanzados|Copiar solicitudes|Últimas 200 solicitudes|Registro de errores de Nginx sin formato|Buscar y reemplazar|encontrar|Reemplazar con|Vista previa de cambios|Vista previa del ensayo|Tablas escaneadas|Partidos en vista previa|Almacenamiento de recuperación|Seleccionar almacenamiento|Haz una copia de seguridad y aplica|La vista previa expiró. Ejecute la vista previa nuevamente.|Sólo se buscan las tablas de WordPress de este sitio. Se omiten las columnas GUID.|Ejecute una vista previa antes de aplicar los cambios.|No se encontraron reemplazos.|Se requiere texto de búsqueda.|El texto de búsqueda debe tener 1024 caracteres o menos.|Historial de copias de seguridad|Fuente|Solicitado|Duración|Resultado|Programado|manuales|Éxito|corriendo|En cola|Punto de restauración listo|Ya no se conserva|Error en la copia de seguridad|Ver trabajo|Aún no se han ejecutado copias de seguridad|Nombre de inicio de sesión|Nombre de usuario o correo electrónico|Contraseña actual|Actualizar nombre de inicio de sesión|Editar usuario|Rol|Permisos de rol|Administrador|Colaborador|Cliente|Administra el servidor, los usuarios y todos los sitios.|Gestiona los sitios asignados.|Gestiona copias de seguridad, registros y WordPress para sitios asignados.|Depurar|Modo de depuración|Registro de depuración de WordPress|Borrar registro|Aún no hay entradas de depuración.|Entradas recientes|Registro del servidor privado|El registro está limitado a los 256 KiB más recientes.|Los errores permanecen ocultos para los visitantes.|La configuración necesita atención",
	"fi":    "Pyydä lokeja|Pyynnöt|Edistyneet suodattimet|Kopioi pyynnöt|200 viimeistä pyyntöä|Raw Nginx-virheloki|Etsi ja vaihda|Etsi|Korvaa kanssa|Esikatsele muutokset|Kuivakäynnistetty esikatselu|Taulukot skannattu|Ottelut esikatselussa|Palautusvarasto|Valitse tallennustila|Varmuuskopioi ja hae|Esikatselu vanhentunut. Suorita esikatselu uudelleen.|Vain tämän sivuston WordPress-taulukoista haetaan. GUID-sarakkeet ohitetaan.|Suorita esikatselu ennen muutosten käyttöönottoa.|Korvaavia ei löytynyt.|Hakuteksti on pakollinen.|Hakutekstin pituus saa olla enintään 1 024 merkkiä.|Varmuuskopiointihistoria|lähde|Pyydetty|Kesto|Tulos|Aikataulutettu|Manuaalinen|Menestystä|Juoksemassa|Jonossa|Palautuspiste on valmis|Ei enää säilytetty|Varmuuskopiointi epäonnistui|Näytä työ|Varmuuskopiointia ei ole vielä suoritettu|Kirjautumisnimi|Käyttäjätunnus tai sähköpostiosoite|Nykyinen salasana|Päivitä kirjautumisnimi|Muokkaa käyttäjää|Rooli|Roolien käyttöoikeudet|Järjestelmänvalvoja|Yhteistyökumppani|Asiakas|Hallitsee palvelinta, käyttäjiä ja kaikkia sivustoja.|Hallitsee määritettyjä sivustoja.|Hallitsee määritettyjen sivustojen varmuuskopioita, lokeja ja WordPressiä.|Debug|Virheenkorjaustila|WordPress-virheenkorjausloki|Tyhjennä loki|Ei vielä virheenkorjausmerkintöjä.|Viimeaikaiset merkinnät|Yksityinen palvelinloki|Loki on rajoitettu viimeisimpään 256 KiB:iin.|Virheet pysyvät piilossa vierailijoilta.|Kokoonpano vaatii huomiota",
	"fr":    "Journaux des requêtes|Demandes|Filtres avancés|Demandes de copie|200 dernières demandes|Journal des erreurs Nginx brut|Rechercher et remplacer|Trouver|Remplacer par|Aperçu des modifications|Aperçu du test à sec|Tableaux numérisés|Matchs en avant-première|Stockage de récupération|Sélectionnez le stockage|Sauvegarder et postuler|L'aperçu a expiré. Exécutez à nouveau l'aperçu.|Seuls les tableaux WordPress de ce site sont recherchés. Les colonnes GUID sont ignorées.|Exécutez un aperçu avant d’appliquer les modifications.|Aucun remplacement trouvé.|Le texte de recherche est requis.|Le texte de recherche doit comporter 1 024 caractères ou moins.|Historique de sauvegarde|Source|Demandé|Durée|Résultat|Programmé|Manuel|Succès|Courir|En file d'attente|Point de restauration prêt|N'est plus retenu|La sauvegarde a échoué|Voir l'emploi|Aucune sauvegarde n'est encore exécutée|Nom de connexion|Nom d'utilisateur ou email|Mot de passe actuel|Mettre à jour le nom de connexion|Modifier l'utilisateur|Rôle|Autorisations de rôle|Administrateur|Collaborateur|Client|Gère le serveur, les utilisateurs et tous les sites.|Gère les sites attribués.|Gère les sauvegardes, les journaux et WordPress pour les sites attribués.|Débogage|Mode débogage|Journal de débogage WordPress|Effacer le journal|Aucune entrée de débogage pour l'instant.|Entrées récentes|Journal du serveur privé|Le journal est limité aux 256 Ko les plus récents.|Les erreurs restent cachées aux visiteurs.|La configuration nécessite une attention particulière",
	"he":    "בקש יומנים|בקשות|מסננים מתקדמים|העתק בקשות|200 בקשות אחרונות|יומן שגיאות Raw Nginx|חפש והחלף|מצא|החלף ב|תצוגה מקדימה של שינויים|תצוגה מקדימה של ריצה יבשה|טבלאות נסרקו|התאמות בתצוגה מקדימה|אחסון שחזור|בחר אחסון|גבה והחל|פג תוקף התצוגה המקדימה. הפעל שוב את התצוגה המקדימה.|מחפשים רק בטבלאות וורדפרס של אתר זה. מדלגים על עמודות GUID.|הפעל תצוגה מקדימה לפני החלת שינויים.|לא נמצאו תחליפים.|נדרש טקסט חיפוש.|טקסט החיפוש חייב להכיל 1,024 תווים או פחות.|היסטוריית גיבוי|מקור|התבקש|משך זמן|תוצאה|מתוזמן|ידני|הצלחה|ריצה|בתור|נקודת שחזור מוכנה|לא נשמר יותר|הגיבוי נכשל|צפה בעבודה|עדיין לא פועל גיבוי|שם כניסה|שם משתמש או אימייל|סיסמה נוכחית|עדכן את שם הכניסה|ערוך משתמש|תפקיד|הרשאות תפקיד|מנהל|משתף פעולה|לקוח|מנהל את השרת, המשתמשים וכל האתרים.|מנהל אתרים שהוקצו.|מנהל גיבויים, יומנים ו- WordPress עבור אתרים שהוקצו.|ניפוי באגים|מצב ניפוי באגים|יומן ניפוי באגים של וורדפרס|נקה יומן|עדיין אין ערכי ניפוי באגים.|ערכים אחרונים|יומן שרת פרטי|היומן מוגבל ל-256 KiB העדכניים ביותר.|שגיאות נשארות מוסתרות מהמבקרים.|תצורה דורשת תשומת לב",
	"hi":    "लॉग का अनुरोध करें|अनुरोध|उन्नत फ़िल्टर|अनुरोध कॉपी करें|पिछले 200 अनुरोध|कच्चा Nginx त्रुटि लॉग|खोजें और बदलें|खोजें|से बदलें|परिवर्तनों का पूर्वावलोकन करें|ड्राई-रन पूर्वावलोकन|तालिकाएँ स्कैन की गईं|पूर्वावलोकन में मिलान|पुनर्प्राप्ति भंडारण|भंडारण का चयन करें|बैकअप लें और आवेदन करें|पूर्वावलोकन समाप्त हो गया. पूर्वावलोकन फिर से चलाएँ.|केवल इस साइट की वर्डप्रेस टेबल ही खोजी जाती हैं। GUID कॉलम छोड़ दिए गए हैं.|परिवर्तन लागू करने से पहले एक पूर्वावलोकन चलाएँ।|कोई प्रतिस्थापन नहीं मिला.|खोज पाठ आवश्यक है.|खोज टेक्स्ट 1,024 वर्ण या उससे कम होना चाहिए।|बैकअप इतिहास|स्रोत|अनुरोध किया|अवधि|नतीजा|अनुसूचित|मैनुअल|सफलता|चल रहा है|कतारबद्ध|पुनर्स्थापना बिंदु तैयार|अब नहीं रखा गया|बैकअप विफल रहा|नौकरी देखें|अभी तक कोई बैकअप नहीं चलता|साइन-इन नाम|उपयोगकर्ता नाम या ईमेल|वर्तमान पासवर्ड|साइन-इन नाम अपडेट करें|उपयोगकर्ता संपादित करें|भूमिका|भूमिका अनुमतियाँ|प्रशासक|सहयोगी|ग्राहक|सर्वर, उपयोगकर्ताओं और सभी साइटों का प्रबंधन करता है।|निर्दिष्ट साइटों का प्रबंधन करता है।|निर्दिष्ट साइटों के लिए बैकअप, लॉग और वर्डप्रेस प्रबंधित करता है।|डीबग करें|डिबग मोड|वर्डप्रेस डिबग लॉग|लॉग साफ़ करें|अभी तक कोई डिबग प्रविष्टियाँ नहीं।|हाल की प्रविष्टियाँ|निजी सर्वर लॉग|लॉग नवीनतम 256 KiB तक सीमित है।|त्रुटियाँ आगंतुकों से छिपी रहती हैं।|कॉन्फ़िगरेशन पर ध्यान देने की आवश्यकता है",
	"hr":    "Zapisi zahtjeva|Zahtjevi|Napredni filteri|Zahtjevi za kopiranje|Zadnjih 200 zahtjeva|Neobrađeni Nginx zapisnik pogrešaka|Traži i zamijeni|pronaći|Zamijenite s|Pregledajte promjene|Pregled rada na suho|Tablice skenirane|Utakmice u pregledu|Pohrana za oporavak|Odaberite pohranu|Napravite sigurnosnu kopiju i primijenite|Pregled je istekao. Ponovno pokrenite pregled.|Pretražuju se samo WordPress tablice ove stranice. GUID stupci su preskočeni.|Pokrenite pregled prije primjene promjena.|Nisu pronađene zamjene.|Potreban je tekst za pretraživanje.|Tekst za pretraživanje mora imati 1024 znaka ili manje.|Povijest sigurnosnog kopiranja|Izvor|Zatraženo|Trajanje|Rezultat|Zakazano|Priručnik|Uspjeh|Trčanje|U redu čekanja|Točka vraćanja spremna|Više se ne zadržava|Sigurnosno kopiranje nije uspjelo|Pogledaj posao|Još nema pokretanja sigurnosne kopije|Ime za prijavu|Korisničko ime ili email|Trenutna lozinka|Ažurirajte ime za prijavu|Uredi korisnika|uloga|Dopuštenja za uloge|Administrator|suradnik|Kupac|Upravlja poslužiteljem, korisnicima i svim stranicama.|Upravlja dodijeljenim mjestima.|Upravlja sigurnosnim kopijama, zapisnicima i WordPressom za dodijeljene stranice.|Debug|Način otklanjanja pogrešaka|WordPress zapisnik otklanjanja pogrešaka|Obriši dnevnik|Još nema unosa otklanjanja pogrešaka.|Nedavni unosi|Dnevnik privatnog poslužitelja|Dnevnik je ograničen na najnovijih 256 KiB.|Pogreške ostaju skrivene od posjetitelja.|Konfiguraciji je potrebna pažnja",
	"hu":    "Kérjen naplókat|Kérések|Speciális szűrők|Kérések másolása|Utolsó 200 kérés|Nyers Nginx hibanapló|Keresés és csere|Keresse meg|Cserélje ki|A módosítások előnézete|Szárazfutásos előnézet|A táblázatok beolvasva|Találatok az előnézetben|Helyreállítási tárhely|Válassza ki a tárhelyet|Készítsen biztonsági másolatot és alkalmazza|Az előnézet lejárt. Futtassa újra az előnézetet.|Csak ennek a webhelynek a WordPress-táblázataiban történik keresés. A GUID oszlopok kimaradnak.|A módosítások alkalmazása előtt futtasson egy előnézetet.|Nem található csere.|Keresendő szöveg kötelező.|A keresett szöveg legfeljebb 1024 karakter lehet.|Biztonsági mentés előzményei|Forrás|Kért|Időtartam|Eredmény|Ütemezett|Kézikönyv|Siker|Futás|Sorban|A visszaállítási pont készen áll|Már nem tartják meg|A biztonsági mentés nem sikerült|Munka megtekintése|Még nem fut a biztonsági mentés|Bejelentkezési név|Felhasználónév vagy email|Jelenlegi jelszó|Frissítse a bejelentkezési nevet|Felhasználó szerkesztése|Szerep|Szerepjogok|Rendszergazda|Munkatárs|Ügyfél|Kezeli a szervert, a felhasználókat és az összes webhelyet.|Kezeli a hozzárendelt webhelyeket.|Kezeli a biztonsági mentéseket, a naplókat és a WordPress-t a hozzárendelt webhelyekhez.|Hibakeresés|Hibakeresési mód|WordPress hibakeresési napló|Napló törlése|Még nincsenek hibakeresési bejegyzések.|Legutóbbi bejegyzések|Privát szervernapló|A napló a legutóbbi 256 KiB-ra korlátozódik.|A hibák rejtve maradnak a látogatók elől.|A konfiguráció figyelmet igényel",
	"id":    "Minta log|Permintaan|Filter tingkat lanjut|Salin permintaan|200 permintaan terakhir|Log kesalahan Nginx mentah|Cari dan ganti|Temukan|Ganti dengan|Pratinjau perubahan|Pratinjau uji coba|Tabel dipindai|Cocok dalam pratinjau|Penyimpanan pemulihan|Pilih penyimpanan|Cadangkan dan terapkan|Pratinjau sudah habis masa berlakunya. Jalankan pratinjau lagi.|Hanya tabel WordPress situs ini yang dicari. Kolom GUID dilewati.|Jalankan pratinjau sebelum menerapkan perubahan.|Tidak ada pengganti yang ditemukan.|Teks pencarian diperlukan.|Teks pencarian harus terdiri dari 1.024 karakter atau kurang.|Riwayat cadangan|Sumber|Diminta|Durasi|Hasil|Dijadwalkan|petunjuk|Sukses|Berlari|Mengantri|Titik pemulihan sudah siap|Tidak lagi dipertahankan|Pencadangan gagal|Lihat pekerjaan|Belum ada pencadangan yang berjalan|Nama masuk|Nama pengguna atau email|Kata sandi saat ini|Perbarui nama masuk|Sunting pengguna|Peran|Izin peran|Administrator|Kolaborator|Pelanggan|Mengelola server, pengguna, dan semua situs.|Mengelola situs yang ditugaskan.|Mengelola cadangan, log, dan WordPress untuk situs yang ditugaskan.|Men-debug|Modus debug|Log debug WordPress|Hapus catatan|Belum ada entri debug.|Entri terbaru|Log server pribadi|Log dibatasi hingga 256 KiB terbaru.|Kesalahan tetap tersembunyi dari pengunjung.|Konfigurasi perlu diperhatikan",
	"it":    "Log delle richieste|Richieste|Filtri avanzati|Copia richieste|Ultime 200 richieste|Registro degli errori Nginx non elaborato|Cerca e sostituisci|Trova|Sostituisci con|Anteprima delle modifiche|Anteprima di prova|Tabelle scansionate|Partite in anteprima|Archiviazione di ripristino|Seleziona spazio di archiviazione|Esegui backup e applica|Anteprima scaduta. Esegui nuovamente l'anteprima.|Vengono cercate solo le tabelle WordPress di questo sito. Le colonne GUID vengono ignorate.|Esegui un'anteprima prima di applicare le modifiche.|Nessun sostituto trovato.|Il testo di ricerca è obbligatorio.|Il testo di ricerca deve contenere al massimo 1.024 caratteri.|Cronologia del backup|Fonte|Richiesto|Durata|Risultato|Programmato|Manuale|Successo|Correre|In coda|Punto di ripristino pronto|Non più trattenuto|Backup non riuscito|Visualizza lavoro|Nessun backup viene ancora eseguito|Nome di accesso|Nome utente o e-mail|Password attuale|Aggiorna il nome di accesso|Modifica utente|Ruolo|Autorizzazioni del ruolo|Amministratore|Collaboratore|Cliente|Gestisce il server, gli utenti e tutti i siti.|Gestisce i siti assegnati.|Gestisce backup, registri e WordPress per i siti assegnati.|Debug|Modalità di debug|Log di debug di WordPress|Cancella registro|Nessuna voce di debug ancora.|Voci recenti|Registro del server privato|Il registro è limitato ai 256 KiB più recenti.|Gli errori rimangono nascosti ai visitatori.|La configurazione richiede attenzione",
	"ja":    "リクエストログ|リクエスト|高度なフィルター|コピーリクエスト|過去 200 件のリクエスト|生の Nginx エラー ログ|検索と置換|探す|と置き換えます|変更のプレビュー|ドライランプレビュー|スキャンされたテーブル|プレビューでの一致|リカバリストレージ|ストレージの選択|バックアップして適用する|プレビューの有効期限が切れました。プレビューを再度実行します。|このサイトの WordPress テーブルのみが検索されます。 GUID 列はスキップされます。|変更を適用する前にプレビューを実行します。|代替品が見つかりませんでした。|検索テキストは必須です。|検索テキストは 1,024 文字以下である必要があります。|バックアップ履歴|ソース|リクエスト済み|期間|結果|予定されている|マニュアル|成功|ランニング|キューに入れられました|復元ポイントの準備ができました|保持されなくなりました|バックアップに失敗しました|ジョブを見る|まだバックアップは実行されていません|サインイン名|ユーザー名またはメールアドレス|現在のパスワード|サインイン名の更新|ユーザーの編集|役割|役割の権限|管理者|協力者|お客様|サーバー、ユーザー、およびすべてのサイトを管理します。|割り当てられたサイトを管理します。|割り当てられたサイトのバックアップ、ログ、WordPress を管理します。|デバッグ|デバッグモード|WordPressのデバッグログ|ログをクリアする|デバッグ エントリはまだありません。|最近のエントリー|プライベートサーバーのログ|ログは最新の 256 KiB に制限されます。|エラーは訪問者から隠されたままになります。|構成には注意が必要です",
	"ko":    "요청 로그|요청사항|고급 필터|요청 복사|최근 200개 요청|원시 Nginx 오류 로그|검색 및 바꾸기|찾기|다음으로 교체|변경사항 미리보기|테스트 실행 미리보기|스캔된 테이블|미리보기에서 일치|복구 스토리지|스토리지 선택|백업하고 신청하세요|미리보기가 만료되었습니다. 미리보기를 다시 실행하세요.|이 사이트의 WordPress 테이블만 검색됩니다. GUID 열을 건너뜁니다.|변경 사항을 적용하기 전에 미리보기를 실행하세요.|대체 항목을 찾을 수 없습니다.|검색 텍스트가 필요합니다.|검색 텍스트는 1,024자 이하여야 합니다.|백업 내역|소스|요청됨|기간|결과|예정됨|매뉴얼|성공|달리기|대기 중|복원 지점 준비됨|더 이상 보관되지 않음|백업 실패|직무 보기|아직 백업이 실행되지 않습니다.|로그인 이름|사용자 이름 또는 이메일|현재 비밀번호|로그인 이름 업데이트|사용자 편집|역할|역할 권한|관리자|협력자|고객|서버, 사용자, 모든 사이트를 관리합니다.|할당된 사이트를 관리합니다.|할당된 사이트에 대한 백업, 로그 및 WordPress를 관리합니다.|디버그|디버그 모드|WordPress 디버그 로그|로그 지우기|아직 디버그 항목이 없습니다.|최근 항목|개인 서버 로그|로그는 가장 최근의 256KiB로 제한됩니다.|오류는 방문자에게 숨겨져 있습니다.|구성에 주의가 필요함",
	"nl":    "Logboeken aanvragen|Verzoeken|Geavanceerde filters|Kopieer verzoeken|Laatste 200 aanvragen|Raw Nginx-foutenlogboek|Zoeken en vervangen|Vind|Vervangen door|Voorbeeld van wijzigingen|Voorbeeld van droogdraaien|Tabellen gescand|Wedstrijden in preview|Herstelopslag|Selecteer opslag|Maak een back-up en solliciteer|Voorbeeld verlopen. Voer het voorbeeld opnieuw uit.|Alleen de WordPress-tabellen van deze site worden doorzocht. GUID-kolommen worden overgeslagen.|Voer een voorbeeld uit voordat u wijzigingen toepast.|Geen vervangingen gevonden.|Zoektekst is vereist.|Zoektekst mag maximaal 1024 tekens lang zijn.|Back-upgeschiedenis|Bron|Gevraagd|Duur|Resultaat|Gepland|Handmatig|Succes|Rennen|In de wachtrij|Herstelpunt gereed|Niet langer behouden|Back-up mislukt|Bekijk vacature|Er zijn nog geen back-ups uitgevoerd|Inlognaam|Gebruikersnaam of e-mailadres|Huidig wachtwoord|Inlognaam bijwerken|Gebruiker bewerken|Rol|Rolmachtigingen|Beheerder|Medewerker|Klant|Beheert de server, gebruikers en alle sites.|Beheert toegewezen sites.|Beheert back-ups, logboeken en WordPress voor toegewezen sites.|Foutopsporing|Debug-modus|WordPress-foutopsporingslogboek|Logboek wissen|Nog geen debug-items.|Recente inzendingen|Privé serverlogboek|Het logboek is beperkt tot de meest recente 256 KiB.|Fouten blijven verborgen voor bezoekers.|Configuratie heeft aandacht nodig",
	"no":    "Be om logger|Forespørsler|Avanserte filtre|Kopier forespørsler|Siste 200 forespørsler|Raw Nginx feillogg|Søk og erstatt|Finn|Bytt ut med|Forhåndsvis endringer|Tørrkjør forhåndsvisning|Tabeller skannet|Kamper i forhåndsvisning|Gjenopprettingslagring|Velg lagring|Sikkerhetskopier og søk|Forhåndsvisningen er utløpt. Kjør forhåndsvisningen på nytt.|Bare dette nettstedets WordPress-tabeller blir søkt. GUID-kolonner hoppes over.|Kjør en forhåndsvisning før du tar i bruk endringer.|Ingen erstatninger funnet.|Søketekst er påkrevd.|Søketekst må bestå av 1024 tegn eller færre.|Sikkerhetskopieringshistorikk|Kilde|Forespurt|Varighet|Resultat|Planlagt|Manuell|Suksess|Løper|I kø|Gjenopprettingspunktet er klart|Ikke lenger beholdt|Sikkerhetskopiering mislyktes|Se jobb|Ingen sikkerhetskopiering kjører ennå|Påloggingsnavn|Brukernavn eller e-post|Gjeldende passord|Oppdater påloggingsnavnet|Rediger bruker|Rolle|Rolletillatelser|Administrator|Samarbeidspartner|Kunde|Administrerer serveren, brukerne og alle nettstedene.|Administrerer tildelte nettsteder.|Administrerer sikkerhetskopier, logger og WordPress for tildelte nettsteder.|Feilsøk|Feilsøkingsmodus|WordPress feilsøkingslogg|Tøm logg|Ingen feilsøkingsoppføringer ennå.|Nylige oppføringer|Privat serverlogg|Loggen er begrenset til de siste 256 KiB.|Feil forblir skjult for besøkende.|Konfigurasjonen trenger oppmerksomhet",
	"pl":    "Poproś o logi|Żądania|Zaawansowane filtry|Kopiuj żądania|Ostatnie 200 żądań|Surowy dziennik błędów Nginx|Wyszukaj i zamień|Znajdź|Zamień na|Podgląd zmian|Podgląd próbny|Zeskanowane tabele|Mecze w podglądzie|Magazyn odzyskiwania|Wybierz pamięć|Utwórz kopię zapasową i zastosuj|Podgląd wygasł. Uruchom ponownie podgląd.|Przeszukiwane są tylko tabele WordPress tej witryny. Kolumny GUID są pomijane.|Uruchom podgląd przed zastosowaniem zmian.|Nie znaleziono zamienników.|Wyszukiwany tekst jest wymagany.|Wyszukiwany tekst może mieć maksymalnie 1024 znaki.|Historia kopii zapasowych|Źródło|Poprosiłem|Czas trwania|Wynik|Zaplanowane|Instrukcja|Sukces|Bieganie|W kolejce|Punkt przywracania gotowy|Nie jest już zachowany|Tworzenie kopii zapasowej nie powiodło się|Zobacz ofertę pracy|Nie wykonano jeszcze żadnych kopii zapasowych|Nazwa logowania|Nazwa użytkownika lub adres e-mail|Aktualne hasło|Zaktualizuj nazwę logowania|Edytuj użytkownika|Rola|Uprawnienia roli|Administrator|Współpracownik|Klient|Zarządza serwerem, użytkownikami i wszystkimi witrynami.|Zarządza przydzielonymi witrynami.|Zarządza kopiami zapasowymi, dziennikami i WordPressem dla przypisanych witryn.|Debuguj|Tryb debugowania|Dziennik debugowania WordPressa|Wyczyść dziennik|Nie ma jeszcze żadnych wpisów debugowania.|Najnowsze wpisy|Prywatny dziennik serwera|Dziennik jest ograniczony do najnowszych 256 KiB.|Błędy pozostają ukryte przed odwiedzającymi.|Konfiguracja wymaga uwagi",
	"pt-BR": "Logs de solicitações|Solicitações|Filtros avançados|Copiar solicitações|Últimas 200 solicitações|Log de erro bruto do Nginx|Pesquisar e substituir|Encontrar|Substitua por|Visualizar alterações|Visualização de simulação|Tabelas verificadas|Partidas em pré-visualização|Armazenamento de recuperação|Selecione armazenamento|Faça backup e aplique|A visualização expirou. Execute a visualização novamente.|Somente as tabelas WordPress deste site são pesquisadas. As colunas GUID são ignoradas.|Execute uma visualização antes de aplicar as alterações.|Nenhum substituto encontrado.|O texto de pesquisa é obrigatório.|O texto de pesquisa deve ter 1.024 caracteres ou menos.|Histórico de backup|Fonte|Solicitado|Duração|Resultado|Agendado|Manuais|Sucesso|Correndo|Na fila|Ponto de restauração pronto|Não é mais retido|Falha no backup|Ver trabalho|Nenhum backup foi executado ainda|Nome de login|Nome de usuário ou e-mail|Senha atual|Atualizar nome de login|Editar usuário|Função|Permissões de função|Administrador|Colaborador|Cliente|Gerencia o servidor, os usuários e todos os sites.|Gerencia sites atribuídos.|Gerencia backups, logs e WordPress para sites atribuídos.|Depurar|Modo de depuração|Registro de depuração do WordPress|Limpar registro|Nenhuma entrada de depuração ainda.|Entradas recentes|Log do servidor privado|O log é limitado aos 256 KiB mais recentes.|Os erros permanecem ocultos aos visitantes.|A configuração precisa de atenção",
	"ro":    "Cereți jurnalele|Cereri|Filtre avansate|Copierea cererilor|Ultimele 200 de cereri|Jurnalul de erori Nginx brut|Căutați și înlocuiți|Găsiți|Înlocuiește cu|Previzualizează modificările|Previzualizare de rulare uscată|Tabelele scanate|Potriviri în previzualizare|Stocare de recuperare|Selectați spațiu de stocare|Faceți backup și aplicați|Previzualizarea a expirat. Rulați din nou previzualizarea.|Sunt căutate doar tabelele WordPress ale acestui site. Coloanele GUID sunt ignorate.|Rulați o previzualizare înainte de a aplica modificările.|Nu s-au găsit înlocuitori.|Este necesar textul de căutare.|Textul de căutare trebuie să aibă 1.024 de caractere sau mai puțin.|Istoricul backupului|Sursa|Solicitat|Durata|Rezultat|Programat|Manual|Succes|Alergarea|În coadă|Punctul de restaurare este gata|Nu mai reținut|Copierea de rezervă a eșuat|Vezi job|Încă nu se execută backup|Nume de conectare|Nume de utilizator sau e-mail|Parola curentă|Actualizați numele de conectare|Editați utilizatorul|Rol|Permisiuni de rol|Administrator|Colaborator|Client|Gestionează serverul, utilizatorii și toate site-urile.|Gestionează site-urile alocate.|Gestionează backup-urile, jurnalele și WordPress pentru site-urile alocate.|Depanați|Modul de depanare|Jurnal de depanare WordPress|Ștergeți jurnalul|Nu există încă intrări de depanare.|Intrări recente|Jurnal de server privat|Jurnalul este limitat la cele mai recente 256 KiB.|Erorile rămân ascunse vizitatorilor.|Configurația necesită atenție",
	"ru":    "Запросить журналы|Запросы|Расширенные фильтры|Копирование запросов|Последние 200 запросов|Необработанный журнал ошибок Nginx|Искать и заменять|Найти|Заменить на|Предварительный просмотр изменений|Предварительный просмотр пробного прогона|Таблицы отсканированы|Матчи в предварительном просмотре|Резервное хранилище|Выберите хранилище|Резервное копирование и применение|Срок действия предварительного просмотра истек. Запустите предварительный просмотр еще раз.|Поиск осуществляется только по таблицам WordPress этого сайта. Столбцы GUID пропускаются.|Прежде чем применять изменения, запустите предварительный просмотр.|Замены не найдены.|Требуется текст поиска.|Текст поиска должен содержать не более 1024 символов.|История резервного копирования|Источник|Запрошено|Продолжительность|Результат|Запланировано|Руководство|Успех|Бег|В очереди|Точка восстановления готова|Больше не сохраняется|Резервное копирование не выполнено|Посмотреть вакансию|Резервное копирование еще не выполнено|Имя для входа|Имя пользователя или адрес электронной почты|Текущий пароль|Обновить имя для входа|Изменить пользователя|Роль|Ролевые разрешения|Администратор|Соавтор|Клиент|Управляет сервером, пользователями и всеми сайтами.|Управляет назначенными сайтами.|Управляет резервными копиями, журналами и WordPress для назначенных сайтов.|Отладка|Режим отладки|Журнал отладки WordPress|Очистить журнал|Отладочных записей пока нет.|Последние записи|Журнал частного сервера|Размер журнала ограничен самыми последними 256 КиБ.|Ошибки остаются скрытыми от посетителей.|Конфигурация требует внимания",
	"sk":    "Vyžiadajte si denníky|Žiadosti|Pokročilé filtre|Kopírovať žiadosti|Posledných 200 žiadostí|Nespracovaný protokol chýb Nginx|Vyhľadajte a nahraďte|Nájsť|Nahradiť za|Ukážka zmien|Ukážka chodu nasucho|Naskenované tabuľky|Zápasy v ukážke|Úložisko obnovy|Vyberte úložisko|Zálohujte a aplikujte|Platnosť ukážky vypršala. Znova spustite ukážku.|Vyhľadávajú sa iba tabuľky WordPress tohto webu. Stĺpce GUID sú preskočené.|Pred použitím zmien spustite ukážku.|Nenašli sa žiadne náhrady.|Vyžaduje sa hľadaný text.|Hľadaný text môže mať maximálne 1 024 znakov.|História zálohovania|Zdroj|Požadované|Trvanie|Výsledok|Naplánované|manuál|Úspech|Beh|Vo fronte|Bod obnovenia pripravený|Už sa nezachováva|Zálohovanie zlyhalo|Zobraziť úlohu|Zatiaľ nie je spustená žiadna záloha|Prihlasovacie meno|Používateľské meno alebo e-mail|Aktuálne heslo|Aktualizujte prihlasovacie meno|Upraviť používateľa|Role|Povolenia rolí|správca|Spolupracovník|Zákazník|Spravuje server, používateľov a všetky lokality.|Spravuje priradené lokality.|Spravuje zálohy, protokoly a WordPress pre priradené lokality.|Debug|Režim ladenia|Denník ladenia WordPress|Vymazať denník|Zatiaľ žiadne položky ladenia.|Najnovšie záznamy|Denník súkromného servera|Denník je obmedzený na najnovších 256 kB.|Chyby zostanú pred návštevníkmi skryté.|Konfigurácia vyžaduje pozornosť",
	"sv":    "Begär loggar|Förfrågningar|Avancerade filter|Kopiera förfrågningar|Senaste 200 förfrågningar|Raw Nginx-fellogg|Sök och ersätt|Hitta|Byt ut med|Förhandsgranska ändringar|Förhandsvisning av torrkörning|Tabeller skannade|Matcher i förhandsvisning|Återställningslagring|Välj lagring|Säkerhetskopiera och ansök|Förhandsvisningen har löpt ut. Kör förhandsgranskningen igen.|Endast den här webbplatsens WordPress-tabeller genomsöks. GUID-kolumner hoppas över.|Kör en förhandsgranskning innan du tillämpar ändringar.|Inga ersättare hittades.|Söktext krävs.|Söktext måste bestå av 1 024 tecken eller färre.|Backup historik|Källa|Begärt|Varaktighet|Resultat|Schemalagt|Manuell|Framgång|Löpning|I kö|Återställningspunkt klar|Behålls inte längre|Säkerhetskopieringen misslyckades|Se jobb|Ingen säkerhetskopiering körs ännu|Inloggningsnamn|Användarnamn eller e-post|Aktuellt lösenord|Uppdatera inloggningsnamn|Redigera användare|Roll|Rollbehörigheter|Administratör|Samarbetspartner|Kund|Hanterar servern, användare och alla webbplatser.|Hanterar tilldelade webbplatser.|Hanterar säkerhetskopior, loggar och WordPress för tilldelade webbplatser.|Felsök|Felsökningsläge|WordPress felsökningslogg|Rensa logg|Inga felsökningsposter ännu.|Senaste inlägg|Privat serverlogg|Loggen är begränsad till de senaste 256 KiB.|Fel förblir dolda för besökare.|Konfigurationen kräver uppmärksamhet",
	"th":    "ขอบันทึก|คำขอ|ตัวกรองขั้นสูง|คัดลอกคำขอ|200 คำขอล่าสุด|บันทึกข้อผิดพลาด Raw Nginx|ค้นหาและแทนที่|ค้นหา|แทนที่ด้วย|ดูตัวอย่างการเปลี่ยนแปลง|การแสดงตัวอย่างการทดลองเรียกใช้|สแกนตารางแล้ว|ตรงกันในหน้าตัวอย่าง|พื้นที่เก็บข้อมูลการกู้คืน|เลือกที่เก็บข้อมูล|สำรองข้อมูลและสมัคร|การแสดงตัวอย่างหมดอายุแล้ว เรียกใช้การแสดงตัวอย่างอีกครั้ง|ค้นหาเฉพาะตาราง WordPress ของไซต์นี้เท่านั้น คอลัมน์ GUID ถูกข้าม|เรียกใช้การแสดงตัวอย่างก่อนที่จะใช้การเปลี่ยนแปลง|ไม่พบสิ่งทดแทน|จำเป็นต้องมีข้อความค้นหา|ข้อความค้นหาต้องมีอักขระไม่เกิน 1,024 ตัว|ประวัติการสำรองข้อมูล|แหล่งที่มา|ร้องขอ|ระยะเวลา|ผลลัพธ์|กำหนดเวลาแล้ว|คู่มือ|ความสำเร็จ|วิ่ง|เข้าคิว|จุดคืนค่าพร้อมแล้ว|ไม่เก็บเอาไว้แล้ว|การสำรองข้อมูลล้มเหลว|ดูงาน|ยังไม่มีการสำรองข้อมูล|ชื่อเข้าสู่ระบบ|ชื่อผู้ใช้หรืออีเมล|รหัสผ่านปัจจุบัน|อัปเดตชื่อการลงชื่อเข้าใช้|แก้ไขผู้ใช้|บทบาท|สิทธิ์ตามบทบาท|ผู้ดูแลระบบ|ผู้ทำงานร่วมกัน|ลูกค้า|จัดการเซิร์ฟเวอร์ ผู้ใช้ และไซต์ทั้งหมด|จัดการไซต์ที่ได้รับมอบหมาย|จัดการการสำรองข้อมูล บันทึก และ WordPress สำหรับไซต์ที่ได้รับมอบหมาย|ดีบัก|โหมดแก้ไขข้อบกพร่อง|บันทึกการแก้ไขข้อบกพร่องของ WordPress|ล้างบันทึก|ยังไม่มีรายการแก้ไขข้อบกพร่อง|รายการล่าสุด|บันทึกเซิร์ฟเวอร์ส่วนตัว|บันทึกถูกจำกัดไว้ที่ 256 KiB ล่าสุด|ข้อผิดพลาดจะถูกซ่อนไม่ให้ผู้เยี่ยมชมเห็น|การกำหนดค่าจำเป็นต้องได้รับการดูแล",
	"tr":    "Günlükleri iste|İstekler|Gelişmiş filtreler|İstekleri kopyala|Son 200 istek|Ham Nginx hata günlüğü|Ara ve değiştir|Bul|Şununla değiştir:|Değişiklikleri önizle|Prova önizlemesi|Taranan tablolar|Önizlemedeki maçlar|Kurtarma depolaması|Depolamayı seçin|Yedekleyin ve uygulayın|Önizlemenin süresi doldu. Önizlemeyi yeniden çalıştırın.|Yalnızca bu sitenin WordPress tabloları aranır. GUID sütunları atlanır.|Değişiklikleri uygulamadan önce bir önizleme çalıştırın.|Değiştirme bulunamadı.|Arama metni gerekli.|Arama metni 1.024 karakter veya daha az olmalıdır.|Yedekleme geçmişi|Kaynak|İstendi|Süre|Sonuç|planlanmış|Manuel|Başarı|Koşu|Sıraya alındı|Geri yükleme noktası hazır|Artık saklanmıyor|Yedekleme başarısız oldu|İşi görüntüle|Henüz yedekleme çalıştırması yok|Oturum açma adı|Kullanıcı adı veya e-posta|Mevcut şifre|Oturum açma adını güncelle|Kullanıcıyı düzenle|Rol|Rol izinleri|Yönetici|İşbirlikçi|Müşteri|Sunucuyu, kullanıcıları ve tüm siteleri yönetir.|Atanan siteleri yönetir.|Atanan siteler için yedeklemeleri, günlükleri ve WordPress'i yönetir.|Hata ayıklama|Hata ayıklama modu|WordPress hata ayıklama günlüğü|Günlüğü temizle|Henüz hata ayıklama girişi yok.|Son girişler|Özel sunucu günlüğü|Günlük, en son 256 KiB ile sınırlıdır.|Hatalar ziyaretçilerden gizlenir.|Yapılandırmaya dikkat edilmesi gerekiyor",
	"uk":    "Журнали запитів|Запити|Розширені фільтри|Копіювати запити|Останні 200 запитів|Необроблений журнал помилок Nginx|Пошук і заміна|знайти|Замінити на|Попередній перегляд змін|Попередній перегляд|Таблиці відскановані|Матчі в попередньому перегляді|Сховище для відновлення|Виберіть сховище|Зробіть резервну копію та застосуйте|Термін попереднього перегляду минув. Знову запустіть попередній перегляд.|Пошук здійснюється лише в таблицях WordPress цього сайту. Стовпці GUID пропускаються.|Запустіть попередній перегляд перед застосуванням змін.|Замін не знайдено.|Пошуковий текст потрібен.|Пошуковий текст має містити 1024 символи або менше.|Історія резервного копіювання|Джерело|Просив|Тривалість|Результат|За розкладом|Інструкція|Успіх|Біг|У черзі|Точка відновлення готова|Більше не зберігається|Помилка резервного копіювання|Переглянути роботу|Резервне копіювання ще не виконується|Ім'я для входу|Ім'я користувача або електронна пошта|Поточний пароль|Оновити ім’я для входу|Редагувати користувача|Роль|Дозволи ролі|Адміністратор|Співробітник|Замовник|Керує сервером, користувачами та всіма сайтами.|Керує закріпленими ділянками.|Керує резервними копіями, журналами та WordPress для призначених сайтів.|Налагодження|Режим налагодження|Журнал налагодження WordPress|Очистити журнал|Поки немає записів про налагодження.|Останні записи|Журнал приватного сервера|Розмір журналу обмежений останніми 256 КБ.|Помилки залишаються прихованими від відвідувачів.|Конфігурація потребує уваги",
	"vi":    "Nhật ký yêu cầu|Yêu cầu|Bộ lọc nâng cao|Sao chép yêu cầu|200 yêu cầu cuối cùng|Nhật ký lỗi Nginx thô|Tìm kiếm và thay thế|Tìm|Thay thế bằng|Xem trước các thay đổi|Xem trước chạy thử|Bàn được quét|Trận đấu trong bản xem trước|Bộ nhớ phục hồi|Chọn bộ nhớ|Sao lưu và áp dụng|Bản xem trước đã hết hạn. Chạy lại bản xem trước.|Chỉ các bảng WordPress của trang này mới được tìm kiếm. Các cột GUID bị bỏ qua.|Chạy bản xem trước trước khi áp dụng thay đổi.|Không tìm thấy sự thay thế.|Văn bản tìm kiếm là bắt buộc.|Văn bản tìm kiếm phải có 1.024 ký tự trở xuống.|Lịch sử sao lưu|Nguồn|Đã yêu cầu|Thời lượng|kết quả|Đã lên lịch|Hướng dẫn sử dụng|thành công|Đang chạy|Đã xếp hàng|Điểm khôi phục đã sẵn sàng|Không còn được giữ lại|Sao lưu không thành công|Xem công việc|Chưa có bản sao lưu nào chạy|Tên đăng nhập|Tên người dùng hoặc email|Mật khẩu hiện tại|Cập nhật tên đăng nhập|Chỉnh sửa người dùng|Vai trò|Quyền của vai trò|Quản trị viên|cộng tác viên|Khách hàng|Quản lý máy chủ, người dùng và tất cả các trang web.|Quản lý các địa điểm được phân công.|Quản lý bản sao lưu, nhật ký và WordPress cho các trang được chỉ định.|Gỡ lỗi|Chế độ gỡ lỗi|Nhật ký gỡ lỗi WordPress|Xóa nhật ký|Chưa có mục gỡ lỗi nào.|Mục nhập gần đây|Nhật ký máy chủ riêng|Nhật ký được giới hạn ở 256 KiB gần đây nhất.|Lỗi được ẩn khỏi khách truy cập.|Cấu hình cần chú ý",
	"zh-CN": "请求日志|要求|高级过滤器|复制请求|最近 200 个请求|原始 Nginx 错误日志|搜索和替换|查找|替换为|预览更改|试运行预览|扫描的表格|预览中的比赛|恢复存储|选择存储|备份并应用|预览已过期。再次运行预览。|仅搜索该站点的 WordPress 表。 GUID 列被跳过。|在应用更改之前运行预览。|没有找到替代品。|需要搜索文本。|搜索文本不得超过 1,024 个字符。|备份历史记录|来源|已请求|持续时间|结果|预定|手册|成功|跑步|排队|还原点准备就绪|不再保留|备份失败|查看职位|尚未运行备份|登录名|用户名或电子邮件|当前密码|更新登录名|编辑用户|角色|角色权限|管理员|合作者|客户|管理服务器、用户和所有站点。|管理分配的站点。|管理指定站点的备份、日志和 WordPress。|调试|调试模式|WordPress 调试日志|清除日志|还没有调试条目。|最近的条目|私服日志|日志仅限于最新的 256 KiB。|错误对访问者来说是隐藏的。|配置需要注意",
	"zh-TW": "請求日誌|要求|進階過濾器|複製請求|最近 200 個請求|原始 Nginx 錯誤日誌|搜尋和替換|尋找|替換為|預覽更改|試運行預覽|掃描的表格|預覽中的比賽|復原儲存|選擇儲存|備份並套用|預覽已過期。再次運行預覽。|僅搜尋網站的 WordPress 表。 GUID 列被跳過。|在應用更改之前運行預覽。|沒有找到替代品。|需要搜尋文字。|搜尋文本不得超過 1,024 個字元。|備份歷史記錄|來源|已請求|持續時間|結果|預定|手冊|成功|跑步|排隊|還原點準備就緒|不再保留|備份失敗|查看職位|尚未運行備份|登入名|使用者名稱或電子郵件|目前密碼|更新登入名|編輯使用者|角色|角色權限|管理員|合作者|客戶|管理伺服器、使用者和所有網站。|管理分配的站點。|管理指定網站的備份、日誌和 WordPress。|偵錯|偵錯模式|WordPress 偵錯日誌|清除日誌|還沒有調試條目。|最近的條目|私服日誌|日誌僅限於最新的 256 KiB。|錯誤對訪客來說是隱藏的。|配置需要注意",
}

// These short labels are ambiguous without their UI context. Keep reviewed
// translations here rather than accepting a generic verb or unrelated noun.
var alpha18ContextCorrections = map[Locale]map[string]string{
	"ar": {"manual": "يدوي", "running": "قيد التشغيل", "matches_in_preview": "التطابقات في المعاينة"},
	"bn": {"manual": "ম্যানুয়াল", "running": "চলমান", "matches_in_preview": "প্রিভিউতে মিল"},
	"ca": {"request_logs": "Registres de sol·licituds", "manual": "Manual", "running": "En execució", "matches_in_preview": "Coincidències a la previsualització"},
	"cs": {"request_logs": "Protokoly požadavků", "manual": "Ruční", "running": "Probíhá", "matches_in_preview": "Shody v náhledu"},
	"da": {"request_logs": "Anmodningslogfiler", "manual": "Manuel", "running": "Kører", "matches_in_preview": "Sammenfald i forhåndsvisningen"},
	"de": {
		"copy_requests":      "Anfragen kopieren",
		"manual":             "Manuell",
		"running":            "Wird ausgeführt",
		"view_job":           "Auftrag anzeigen",
		"no_backup_runs_yet": "Noch keine Sicherungsläufe",
		"matches_in_preview": "Treffer in der Vorschau",
	},
	"el": {"manual": "Χειροκίνητα", "running": "Σε εξέλιξη", "matches_in_preview": "Αντιστοιχίες στην προεπισκόπηση"},
	"es": {"manual": "Manual", "running": "En ejecución", "matches_in_preview": "Coincidencias en la vista previa"},
	"fi": {"request_logs": "Pyyntölokit", "manual": "Manuaalinen", "running": "Käynnissä", "matches_in_preview": "Osumat esikatselussa"},
	"fr": {"copy_requests": "Copier les requêtes", "manual": "Manuel", "running": "En cours", "matches_in_preview": "Correspondances dans l’aperçu"},
	"he": {"manual": "ידני", "running": "פועל", "matches_in_preview": "התאמות בתצוגה המקדימה"},
	"hi": {"manual": "मैन्युअल", "running": "चल रहा है", "matches_in_preview": "पूर्वावलोकन में मिलान"},
	"hr": {"manual": "Ručno", "running": "U tijeku", "matches_in_preview": "Podudaranja u pregledu"},
	"hu": {"manual": "Kézi", "running": "Folyamatban", "matches_in_preview": "Találatok az előnézetben"},
	"id": {"manual": "Manual", "running": "Sedang berjalan", "matches_in_preview": "Kecocokan dalam pratinjau"},
	"it": {
		"matches_in_preview": "Corrispondenze nell’anteprima",
		"running":            "In esecuzione",
		"view_job":           "Visualizza attività",
		"no_backup_runs_yet": "Ancora nessuna esecuzione di backup",
		"no_debug_entries":   "Ancora nessuna voce di debug.",
		"private_server_log": "Log privato del server",
	},
	"ja": {
		"find":               "検索",
		"replace_with":       "置換後",
		"manual":             "手動",
		"running":            "実行中",
		"queued":             "待機中",
		"view_job":           "ジョブを表示",
		"no_backup_runs_yet": "バックアップ実行履歴はまだありません",
	},
	"ko":    {"manual": "수동", "running": "실행 중", "matches_in_preview": "미리보기의 일치 항목"},
	"nl":    {"manual": "Handmatig", "running": "Wordt uitgevoerd", "matches_in_preview": "Overeenkomsten in voorbeeld"},
	"no":    {"manual": "Manuell", "running": "Kjører", "matches_in_preview": "Treff i forhåndsvisningen"},
	"pl":    {"manual": "Ręcznie", "running": "W toku", "matches_in_preview": "Dopasowania w podglądzie"},
	"pt-BR": {"manual": "Manual", "running": "Em execução", "matches_in_preview": "Correspondências na prévia"},
	"ro":    {"request_logs": "Jurnale de cereri", "manual": "Manual", "running": "În curs", "matches_in_preview": "Potriviri în previzualizare"},
	"ru":    {"request_logs": "Журналы запросов", "manual": "Вручную", "running": "Выполняется", "matches_in_preview": "Совпадения в предпросмотре"},
	"sk":    {"request_logs": "Denníky požiadaviek", "manual": "Manuálne", "running": "Prebieha", "matches_in_preview": "Zhody v ukážke"},
	"sv":    {"request_logs": "Förfrågningsloggar", "manual": "Manuell", "running": "Körs", "matches_in_preview": "Träffar i förhandsgranskningen"},
	"th":    {"request_logs": "บันทึกคำขอ", "manual": "ด้วยตนเอง", "running": "กำลังทำงาน", "matches_in_preview": "รายการที่ตรงกันในการแสดงตัวอย่าง"},
	"tr":    {"request_logs": "İstek günlükleri", "manual": "Manuel", "running": "Çalışıyor", "matches_in_preview": "Önizlemedeki eşleşmeler"},
	"uk":    {"manual": "Вручну", "running": "Виконується", "matches_in_preview": "Збіги в попередньому перегляді"},
	"vi":    {"manual": "Thủ công", "running": "Đang chạy", "matches_in_preview": "Kết quả khớp trong bản xem trước"},
	"zh-CN": {
		"request_logs":       "请求日志",
		"requests":           "请求",
		"copy_requests":      "复制请求",
		"matches_in_preview": "预览中的匹配项",
		"manual":             "手动",
		"running":            "运行中",
		"queued":             "已排队",
		"view_job":           "查看任务",
		"no_backup_runs_yet": "暂无备份运行记录",
	},
	"zh-TW": {
		"request_logs":       "要求日誌",
		"requests":           "要求",
		"copy_requests":      "複製要求",
		"matches_in_preview": "預覽中的相符項目",
		"manual":             "手動",
		"running":            "執行中",
		"queued":             "已排入佇列",
		"view_job":           "檢視工作",
		"no_backup_runs_yet": "尚無備份執行記錄",
	},
}

func init() {
	for locale, values := range selectorWords {
		catalog[locale]["language"] = values[0]
		catalog[locale]["apply"] = values[1]
	}
	for locale, values := range navigationWords {
		for index, key := range navigationKeys {
			catalog[locale][key] = values[index]
		}
	}
	for locale, actions := range actionWords {
		for index, action := range actions {
			catalog[locale][actionKeys[index]] = action
		}
	}
	for locale, joined := range fieldWords {
		values := strings.Split(joined, "|")
		if len(values) != len(fieldKeys) {
			panic("localization field catalog has wrong length for " + string(locale))
		}
		for index, value := range values {
			catalog[locale][fieldKeys[index]] = value
		}
	}
	for locale, joined := range fileWords {
		values := strings.Split(joined, "|")
		if len(values) != len(fileKeys) {
			panic("localization file catalog has wrong length for " + string(locale))
		}
		for index, value := range values {
			catalog[locale][fileKeys[index]] = value
		}
	}
	for locale, joined := range commonWords {
		values := strings.Split(joined, "|")
		if len(values) != len(commonKeys) {
			panic("localization common catalog has wrong length for " + string(locale))
		}
		for index, value := range values {
			catalog[locale][commonKeys[index]] = value
		}
	}
	for locale, joined := range alpha18Words {
		values := strings.Split(joined, "|")
		if len(values) != len(alpha18Keys) {
			panic("localization alpha18 catalog has wrong length for " + string(locale))
		}
		for index, value := range values {
			catalog[locale][alpha18Keys[index]] = value
		}
	}
	for locale, corrections := range alpha18ContextCorrections {
		for key, value := range corrections {
			catalog[locale][key] = value
		}
	}
}

func words(values ...string) map[string]string {
	result := make(map[string]string, len(keys))
	for index, value := range values {
		result[keys[index]] = value
	}
	return result
}
