package monitor

import (
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"strconv"
	"strings"
	"time"
)

// Proc files are generated by the kernel, but a bound also protects tests and
// unusual mounts from turning one monitoring sample into an unbounded read.
const maxProcBytes = 4 << 20

func readProc(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, maxProcBytes+1))
	if err != nil {
		return "", err
	}
	if len(data) > maxProcBytes {
		return "", errors.New("proc file exceeds monitoring read limit")
	}
	return string(data), nil
}

func parseCPU(data string) (CPUCounters, int, error) {
	var counters CPUCounters
	var found bool
	var count int
	for _, line := range strings.Split(data, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if fields[0] != "cpu" {
			if strings.HasPrefix(fields[0], "cpu") {
				if _, err := strconv.ParseUint(strings.TrimPrefix(fields[0], "cpu"), 10, 32); err == nil {
					count++
				}
			}
			continue
		}
		if found || len(fields) < 5 {
			return CPUCounters{}, 0, errors.New("invalid aggregate CPU counters")
		}
		found = true
		// Guest and guest_nice are already included in user and nice. Only the
		// first eight columns contribute to total; counting guests twice would
		// overstate utilization on virtualized hosts.
		for i := 1; i < len(fields) && i <= 8; i++ {
			value, err := strconv.ParseUint(fields[i], 10, 64)
			if err != nil || value > math.MaxUint64-counters.Total {
				return CPUCounters{}, 0, errors.New("invalid aggregate CPU counter value")
			}
			counters.Total += value
			// Idle and I/O wait are both non-busy CPU time. Disk congestion
			// must not masquerade as CPU work in the dashboard.
			if i != 4 && i != 5 {
				counters.Busy += value
			}
		}
	}
	if !found || count == 0 {
		return CPUCounters{}, 0, errors.New("missing CPU counters or logical CPUs")
	}
	return counters, count, nil
}

func parseMemory(data string) (total, available, swapTotal, swapFree uint64, err error) {
	values := make(map[string]uint64, 4)
	for _, line := range strings.Split(data, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		name := strings.TrimSuffix(fields[0], ":")
		switch name {
		case "MemTotal", "MemAvailable", "SwapTotal", "SwapFree":
		default:
			continue
		}
		if _, exists := values[name]; exists || len(fields) != 3 || fields[2] != "kB" {
			return 0, 0, 0, 0, fmt.Errorf("invalid %s memory counter", name)
		}
		value, parseErr := strconv.ParseUint(fields[1], 10, 64)
		if parseErr != nil || value > math.MaxUint64/1024 {
			return 0, 0, 0, 0, fmt.Errorf("invalid %s memory counter", name)
		}
		values[name] = value * 1024
	}
	total, hasTotal := values["MemTotal"]
	available, hasAvailable := values["MemAvailable"]
	if !hasTotal || !hasAvailable || total == 0 || available > total {
		return 0, 0, 0, 0, errors.New("missing or inconsistent memory totals")
	}
	swapTotal, hasSwapTotal := values["SwapTotal"]
	swapFree, hasSwapFree := values["SwapFree"]
	if hasSwapTotal != hasSwapFree || swapFree > swapTotal {
		return 0, 0, 0, 0, errors.New("inconsistent swap totals")
	}
	return total, available, swapTotal, swapFree, nil
}

func parseNetwork(data string) (map[string]NetworkCounters, error) {
	counters := make(map[string]NetworkCounters)
	var found bool
	for _, line := range strings.Split(data, "\n") {
		name, values, ok := strings.Cut(line, ":")
		if !ok {
			continue // The two kernel headings contain no interface counters.
		}
		name = strings.TrimSpace(name)
		fields := strings.Fields(values)
		if name == "" || len(fields) != 16 {
			return nil, errors.New("invalid network interface counters")
		}
		found = true
		if _, exists := counters[name]; exists {
			return nil, errors.New("duplicate network interface counters")
		}
		var item NetworkCounters
		for i, field := range fields {
			value, err := strconv.ParseUint(field, 10, 64)
			if err != nil {
				return nil, fmt.Errorf("invalid network counter for %s", name)
			}
			switch i {
			case 0:
				item.Received = value
			case 8:
				item.Sent = value
			}
		}
		if name != "lo" {
			counters[name] = item
		}
	}
	if !found {
		return nil, errors.New("missing network interface counters")
	}
	return counters, nil
}

func parseLoad(data string) (one, five, fifteen float64, err error) {
	fields := strings.Fields(data)
	if len(fields) < 3 {
		return 0, 0, 0, errors.New("missing load averages")
	}
	var values [3]float64
	for i := range values {
		value, parseErr := strconv.ParseFloat(fields[i], 64)
		if parseErr != nil || !finitePositive(value) {
			return 0, 0, 0, errors.New("invalid load average")
		}
		values[i] = value
	}
	return values[0], values[1], values[2], nil
}

func parseUptime(data string) (time.Duration, error) {
	fields := strings.Fields(data)
	if len(fields) == 0 {
		return 0, errors.New("missing uptime")
	}
	seconds, err := strconv.ParseFloat(fields[0], 64)
	if err != nil || !finitePositive(seconds) || seconds >= float64(math.MaxInt64)/float64(time.Second) {
		return 0, errors.New("invalid uptime")
	}
	return time.Duration(seconds * float64(time.Second)), nil
}

func finitePositive(value float64) bool {
	return !math.IsNaN(value) && !math.IsInf(value, 0) && value >= 0
}
